package com.maven.util;

import java.io.Serializable;

/**
 * Model class of permission_menu.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RelactionMenu implements Serializable{

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** menucode. */
	private String menucode;

	/** 菜单标题. */
	private String menuname;

	/** 菜单英文名 */
	private String englishname;
	
	/** 父菜单ID. */
	private String parentmenucode;
	
	/** 父菜单标题. */
	private String parentmenuname;
	
	/** 父菜单英文名 */
	private String parentenglishname;
	
	/** 父标题url */
	private String parenturl;
	
	
	public RelactionMenu(String menucode,String menuname, String englishname, String parentmenucode,String parentmenuname,String parentenglishname, String parenturl){
		this.menucode = menucode;
		this.menuname = menuname;
		this.englishname = englishname;
		this.parentmenucode = parentmenucode;
		this.parentmenuname = parentmenuname;
		this.parentenglishname = parentenglishname;
		this.parenturl = parenturl;
	}

	public String getMenucode() {
		return menucode;
	}

	public void setMenucode(String menucode) {
		this.menucode = menucode;
	}

	public String getMenuname() {
		return menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	public String getParentmenucode() {
		return parentmenucode;
	}

	public void setParentmenucode(String parentmenucode) {
		this.parentmenucode = parentmenucode;
	}

	public String getParentmenuname() {
		return parentmenuname;
	}

	public void setParentmenuname(String parentmenuname) {
		this.parentmenuname = parentmenuname;
	}

	public String getParenturl() {
		return parenturl;
	}

	public void setParenturl(String parenturl) {
		this.parenturl = parenturl;
	}

	public String getEnglishname() {
		return englishname;
	}

	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}

	public String getParentenglishname() {
		return parentenglishname;
	}

	public void setParentenglishname(String parentenglishname) {
		this.parentenglishname = parentenglishname;
	}
}