package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of activity_reg_bonus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityRegBonus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer regbonuscode;

	/** 用户编码. */
	private String employeecode;

	/** 用户上级编码. */
	private String parentemployeecode;

	/** 用户账号. */
	private String loginaccount;

	/** 领取时间. */
	private Date gettime;

	/** 奖金金额. */
	private Double regbonus;

	/** 身份认证信息. */
	private String uniqueinfo;

	/**
	 * Constructor.
	 */
	public ActivityRegBonus() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param regbonuscode
	 *            主键
	 */
	public void setRegbonuscode(Integer regbonuscode) {
		this.regbonuscode = regbonuscode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getRegbonuscode() {
		return this.regbonuscode;
	}

	/**
	 * Set the 用户编码.
	 * 
	 * @param employeecode
	 *            用户编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 用户编码.
	 * 
	 * @return 用户编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 用户上级编码.
	 * 
	 * @param parentemployeecode
	 *            用户上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 用户上级编码.
	 * 
	 * @return 用户上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账号.
	 * 
	 * @param loginaccount
	 *            用户账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账号.
	 * 
	 * @return 用户账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 领取时间.
	 * 
	 * @param gettime
	 *            领取时间
	 */
	public void setGettime(Date gettime) {
		this.gettime = gettime;
	}

	/**
	 * Get the 领取时间.
	 * 
	 * @return 领取时间
	 */
	public Date getGettime() {
		return this.gettime;
	}

	/**
	 * Set the 奖金金额.
	 * 
	 * @param regbonus
	 *            奖金金额
	 */
	public void setRegbonus(Double regbonus) {
		this.regbonus = regbonus;
	}

	/**
	 * Get the 奖金金额.
	 * 
	 * @return 奖金金额
	 */
	public Double getRegbonus() {
		return this.regbonus;
	}

	/**
	 * Set the 身份认证信息.
	 * 
	 * @param uniqueinfo
	 *            身份认证信息
	 */
	public void setUniqueinfo(String uniqueinfo) {
		this.uniqueinfo = uniqueinfo;
	}

	/**
	 * Get the 身份认证信息.
	 * 
	 * @return 身份认证信息
	 */
	public String getUniqueinfo() {
		return this.uniqueinfo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((regbonuscode == null) ? 0 : regbonuscode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityRegBonus other = (ActivityRegBonus) obj;
		if (regbonuscode == null) {
			if (other.regbonuscode != null) {
				return false;
			}
		} else if (!regbonuscode.equals(other.regbonuscode)) {
			return false;
		}
		return true;
	}
	
	/**
	 * 红包模板参数
	 * @author king
	 *
	 */
	public enum RegBonusModelSettings{
		HBSX("HBSX","红包上限"),
		HBXX("HBXX","红包下限"),
		LSBS("LSBS","流水倍数");
		public String value;
		public String desc;
		
		private RegBonusModelSettings(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
}
