package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of activity_raffle_control.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityRaffleControl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer rafflecontrolcode;

	/** 用户编码. */
	private String employeecode;

	/** 用户上级编码. */
	private String parentemployeecode;

	/** 用户账号. */
	private String loginaccount;

	/** 当前可用抽奖次数. */
	private Integer availabletimes;

	/** 已完成抽奖次数. */
	private Integer finishtimes;
	
	/** 赠送时间 */
	private Date donatedate;
	
	private int ecactivitycode;//
	private int createdate;//yyyyMMdd
	private Date createtime;//记录创建时间
	
	/** 用户唯一浏览器识别码. */
	private String fingerprintcode;
	/** 登录IP. */
	private String loginip;

	/**
	 * Constructor.
	 */
	public ActivityRaffleControl() {
	}
	
	public ActivityRaffleControl(Integer rafflecontrolcode,Integer availabletimes,Integer finishtimes) {
		this.rafflecontrolcode = rafflecontrolcode;
		this.availabletimes = availabletimes;
		this.finishtimes = finishtimes;
	}
	
	/**
	 * Set the 主键.
	 * 
	 * @param rafflecontrolcode
	 *            主键
	 */
	public void setRafflecontrolcode(Integer rafflecontrolcode) {
		this.rafflecontrolcode = rafflecontrolcode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getRafflecontrolcode() {
		return this.rafflecontrolcode;
	}

	/**
	 * Set the 用户编码.
	 * 
	 * @param employeecode
	 *            用户编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 用户编码.
	 * 
	 * @return 用户编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 用户上级编码.
	 * 
	 * @param parentemployeecode
	 *            用户上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 用户上级编码.
	 * 
	 * @return 用户上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账号.
	 * 
	 * @param loginaccount
	 *            用户账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账号.
	 * 
	 * @return 用户账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 当前可用抽奖次数.
	 * 
	 * @param availabletimes
	 *            当前可用抽奖次数
	 */
	public void setAvailabletimes(Integer availabletimes) {
		this.availabletimes = availabletimes;
	}

	/**
	 * Get the 当前可用抽奖次数.
	 * 
	 * @return 当前可用抽奖次数
	 */
	public Integer getAvailabletimes() {
		return this.availabletimes;
	}

	/**
	 * Set the 已完成抽奖次数.
	 * 
	 * @param finishtimes
	 *            已完成抽奖次数
	 */
	public void setFinishtimes(Integer finishtimes) {
		this.finishtimes = finishtimes;
	}

	/**
	 * Get the 已完成抽奖次数.
	 * 
	 * @return 已完成抽奖次数
	 */
	public Integer getFinishtimes() {
		return this.finishtimes;
	}

	public Date getDonatedate() {
		return donatedate;
	}

	public void setDonatedate(Date donatedate) {
		this.donatedate = donatedate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rafflecontrolcode == null) ? 0 : rafflecontrolcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityRaffleControl other = (ActivityRaffleControl) obj;
		if (rafflecontrolcode == null) {
			if (other.rafflecontrolcode != null) {
				return false;
			}
		} else if (!rafflecontrolcode.equals(other.rafflecontrolcode)) {
			return false;
		}
		return true;
	}

	public int getEcactivitycode() {
		return ecactivitycode;
	}

	public void setEcactivitycode(int ecactivitycode) {
		this.ecactivitycode = ecactivitycode;
	}

	public int getCreatedate() {
		return createdate;
	}

	public void setCreatedate(int createdate) {
		this.createdate = createdate;
	}

	public Date getCreatetime() {
		return createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getFingerprintcode() {
		return fingerprintcode;
	}

	public void setFingerprintcode(String fingerprintcode) {
		this.fingerprintcode = fingerprintcode;
	}

	public String getLoginip() {
		return loginip;
	}

	public void setLoginip(String loginip) {
		this.loginip = loginip;
	}

}
