package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of activity_lose_bonus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityLoseBonus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer losebonuscode;

	/** 用户编码. */
	private String employeecode;

	/** 用户上级编码. */
	private String parentemployeecode;

	/** 用户账号. */
	private String loginaccount;

	/** 上月输钱金额. */
	private Double loseamount;

	/** 返奖比率. */
	private Short returnratio;

	/** 返奖金额. */
	private Double returnamount;

	/** 领取时间. */
	private Date gettime;

	/** 是否派发 0未派发 1已派发. */
	private String losebonusstatus;

	/** 身份认证信息. */
	private String uniqueinfo;

	/**
	 * Constructor.
	 */
	public ActivityLoseBonus() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param losebonuscode
	 *            主键
	 */
	public void setLosebonuscode(Integer losebonuscode) {
		this.losebonuscode = losebonuscode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getLosebonuscode() {
		return this.losebonuscode;
	}

	/**
	 * Set the 用户编码.
	 * 
	 * @param employeecode
	 *            用户编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 用户编码.
	 * 
	 * @return 用户编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 用户上级编码.
	 * 
	 * @param parentemployeecode
	 *            用户上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 用户上级编码.
	 * 
	 * @return 用户上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账号.
	 * 
	 * @param loginaccount
	 *            用户账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账号.
	 * 
	 * @return 用户账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 上月输钱金额.
	 * 
	 * @param loseamount
	 *            上月输钱金额
	 */
	public void setLoseamount(Double loseamount) {
		this.loseamount = loseamount;
	}

	/**
	 * Get the 上月输钱金额.
	 * 
	 * @return 上月输钱金额
	 */
	public Double getLoseamount() {
		return this.loseamount;
	}

	/**
	 * Set the 返奖比率.
	 * 
	 * @param returnratio
	 *            返奖比率
	 */
	public void setReturnratio(Short returnratio) {
		this.returnratio = returnratio;
	}

	/**
	 * Get the 返奖比率.
	 * 
	 * @return 返奖比率
	 */
	public Short getReturnratio() {
		return this.returnratio;
	}

	/**
	 * Set the 返奖金额.
	 * 
	 * @param returnamount
	 *            返奖金额
	 */
	public void setReturnamount(Double returnamount) {
		this.returnamount = returnamount;
	}

	/**
	 * Get the 返奖金额.
	 * 
	 * @return 返奖金额
	 */
	public Double getReturnamount() {
		return this.returnamount;
	}

	/**
	 * Set the 领取时间.
	 * 
	 * @param gettime
	 *            领取时间
	 */
	public void setGettime(Date gettime) {
		this.gettime = gettime;
	}

	/**
	 * Get the 领取时间.
	 * 
	 * @return 领取时间
	 */
	public Date getGettime() {
		return this.gettime;
	}

	/**
	 * Set the 是否派发 0未派发 1已派发.
	 * 
	 * @param losebonusstatus
	 *            是否派发 0未派发 1已派发
	 */
	public void setLosebonusstatus(String losebonusstatus) {
		this.losebonusstatus = losebonusstatus;
	}

	/**
	 * Get the 是否派发 0未派发 1已派发.
	 * 
	 * @return 是否派发 0未派发 1已派发
	 */
	public String getLosebonusstatus() {
		return this.losebonusstatus;
	}

	/**
	 * Set the 身份认证信息.
	 * 
	 * @param uniqueinfo
	 *            身份认证信息
	 */
	public void setUniqueinfo(String uniqueinfo) {
		this.uniqueinfo = uniqueinfo;
	}

	/**
	 * Get the 身份认证信息.
	 * 
	 * @return 身份认证信息
	 */
	public String getUniqueinfo() {
		return this.uniqueinfo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((losebonuscode == null) ? 0 : losebonuscode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityLoseBonus other = (ActivityLoseBonus) obj;
		if (losebonuscode == null) {
			if (other.losebonuscode != null) {
				return false;
			}
		} else if (!losebonuscode.equals(other.losebonuscode)) {
			return false;
		}
		return true;
	}

	/**
	 * 上月输值返模板参数
	 * @author king
	 *
	 */
	public enum LoseBonusModelSettings{
		FLBFB("FLBFB","返利百分比"),
		DUTYHJE("DUTYHJE","是否扣除优惠"),
		LSBS("LSBS","流水倍数"),
		;
		public String value;
		public String desc;
		
		private LoseBonusModelSettings(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	/**
	 * 上月输值返模板参数
	 * @author king
	 *
	 */
	public enum Enum_LoseBonusStatus{
		未派发("0","未派发"),
		已派发("1","已派发"),
		;
		public String value;
		public String desc;
		
		private Enum_LoseBonusStatus(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
}
