package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of activity_template_setting.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityTemplateSetting implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 活动配置编码. */
	private Integer activitysettingcode;

	/** 活动编码. */
	private Integer activitycode;

	/** 参数. */
	private String agementname;

	/** 参数描述. */
	private String agementdesc;

	/* 不共享活动描述 */
	private String unsharedesc;
	
	/* 活动名称 */
	private String activityname;
	
	/* 加密字段:唯一标识 */
	private String sign;
	
	/**
	 * Constructor.
	 */
	public ActivityTemplateSetting() {
	}
	
	public ActivityTemplateSetting(Integer activitycode) {
		this.activitycode = activitycode;
	}

	/**
	 * Set the 活动配置编码.
	 * 
	 * @param activitysettingcode
	 *            活动配置编码
	 */
	public void setActivitysettingcode(Integer activitysettingcode) {
		this.activitysettingcode = activitysettingcode;
	}

	/**
	 * Get the 活动配置编码.
	 * 
	 * @return 活动配置编码
	 */
	public Integer getActivitysettingcode() {
		return this.activitysettingcode;
	}

	/**
	 * Set the 活动编码.
	 * 
	 * @param activitycode
	 *            活动编码
	 */
	public void setActivitycode(Integer activitycode) {
		this.activitycode = activitycode;
	}

	/**
	 * Get the 活动编码.
	 * 
	 * @return 活动编码
	 */
	public Integer getActivitycode() {
		return this.activitycode;
	}

	/**
	 * Set the 参数.
	 * 
	 * @param agementname
	 *            参数
	 */
	public void setAgementname(String agementname) {
		this.agementname = agementname;
	}

	/**
	 * Get the 参数.
	 * 
	 * @return 参数
	 */
	public String getAgementname() {
		return this.agementname;
	}

	/**
	 * Set the 参数描述.
	 * 
	 * @param agementdesc
	 *            参数描述
	 */
	public void setAgementdesc(String agementdesc) {
		this.agementdesc = agementdesc;
	}

	/**
	 * Get the 参数描述.
	 * 
	 * @return 参数描述
	 */
	public String getAgementdesc() {
		return this.agementdesc;
	}


	public String getUnsharedesc() {
		return unsharedesc;
	}

	public void setUnsharedesc(String unsharedesc) {
		this.unsharedesc = unsharedesc;
	}

	public String getActivityname() {
		return activityname;
	}

	public void setActivityname(String activityname) {
		this.activityname = activityname;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((activitysettingcode == null) ? 0 : activitysettingcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityTemplateSetting other = (ActivityTemplateSetting) obj;
		if (activitysettingcode == null) {
			if (other.activitysettingcode != null) {
				return false;
			}
		} else if (!activitysettingcode.equals(other.activitysettingcode)) {
			return false;
		}
		return true;
	}

}
