package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of activity_deposit_bonus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityDepositBonus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private String ordernumber;

	/** 用户编码. */
	private String employeecode;

	/** 用户上级编码. */
	private String parentemployeecode;

	/** 用户账号. */
	private String loginaccount;
	
	/** 存款类型. */
	private String depositType;

	/** 充值金额. */
	private Double depositamount;

	/** 返奖比率. */
	private Double returnratio;

	/** 返奖金额. */
	private Double returnamount;

	/** 充值时间. */
	private Date deposittime;

	/** 领取时间. */
	private Date gettime;

	/** 身份认证信息. */
	private String uniqueinfo;

	/**
	 * Constructor.
	 */
	public ActivityDepositBonus() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param depositbonuscode
	 *            主键
	 */
	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getOrdernumber() {
		return this.ordernumber;
	}

	/**
	 * Set the 用户编码.
	 * 
	 * @param employeecode
	 *            用户编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 用户编码.
	 * 
	 * @return 用户编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 用户上级编码.
	 * 
	 * @param parentemployeecode
	 *            用户上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 用户上级编码.
	 * 
	 * @return 用户上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账号.
	 * 
	 * @param loginaccount
	 *            用户账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账号.
	 * 
	 * @return 用户账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 充值金额.
	 * 
	 * @param depositamount
	 *            充值金额
	 */
	public void setDepositamount(Double depositamount) {
		this.depositamount = depositamount;
	}

	/**
	 * Get the 充值金额.
	 * 
	 * @return 充值金额
	 */
	public Double getDepositamount() {
		return this.depositamount;
	}

	/**
	 * Set the 返奖比率.
	 * 
	 * @param returnratio
	 *            返奖比率
	 */
	public void setReturnratio(Double returnratio) {
		this.returnratio = returnratio;
	}

	/**
	 * Get the 返奖比率.
	 * 
	 * @return 返奖比率
	 */
	public Double getReturnratio() {
		return this.returnratio;
	}

	/**
	 * Set the 返奖金额.
	 * 
	 * @param returnamount
	 *            返奖金额
	 */
	public void setReturnamount(Double returnamount) {
		this.returnamount = returnamount;
	}

	/**
	 * Get the 返奖金额.
	 * 
	 * @return 返奖金额
	 */
	public Double getReturnamount() {
		return this.returnamount;
	}

	/**
	 * Set the 充值时间.
	 * 
	 * @param deposittime
	 *            充值时间
	 */
	public void setDeposittime(Date deposittime) {
		this.deposittime = deposittime;
	}

	/**
	 * Get the 充值时间.
	 * 
	 * @return 充值时间
	 */
	public Date getDeposittime() {
		return this.deposittime;
	}

	/**
	 * Set the 领取时间.
	 * 
	 * @param gettime
	 *            领取时间
	 */
	public void setGettime(Date gettime) {
		this.gettime = gettime;
	}

	/**
	 * Get the 领取时间.
	 * 
	 * @return 领取时间
	 */
	public Date getGettime() {
		return this.gettime;
	}

	public String getDepositType() {
		return depositType;
	}

	public void setDepositType(String depositType) {
		this.depositType = depositType;
	}

	/**
	 * Set the 身份认证信息.
	 * 
	 * @param uniqueinfo
	 *            身份认证信息
	 */
	public void setUniqueinfo(String uniqueinfo) {
		this.uniqueinfo = uniqueinfo;
	}

	/**
	 * Get the 身份认证信息.
	 * 
	 * @return 身份认证信息
	 */
	public String getUniqueinfo() {
		return this.uniqueinfo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ordernumber == null) ? 0 : ordernumber.hashCode());
		return result;
	}
	

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityDepositBonus other = (ActivityDepositBonus) obj;
		if (ordernumber == null) {
			if (other.ordernumber != null) {
				return false;
			}
		} else if (!ordernumber.equals(other.ordernumber)) {
			return false;
		}
		return true;
	}
	
	/**
	 * 存款返模板参数
	 * @author king
	 *
	 */
	public enum DepositBonusModelSettings{
		FLBFB("FLBFB","返利百分比"),
		LSBS("LSBS","流水倍数"),
		;
		public String value;
		public String desc;
		
		private DepositBonusModelSettings(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
}
