package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of activity_raffle_signin.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivityRaffleSignin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer rafflesignincode;

	/** 用户编码. */
	private String employeecode;

	/** 签到时间. */
	private Date signintime;

	/** 充值金额. */
	private Double depositamount;

	/** 打码金额. */
	private Double betamount;
	
	/**
	 * Constructor.
	 */
	public ActivityRaffleSignin() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param rafflesignincode
	 *            主键
	 */
	public void setRafflesignincode(Integer rafflesignincode) {
		this.rafflesignincode = rafflesignincode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getRafflesignincode() {
		return this.rafflesignincode;
	}

	/**
	 * Set the 用户编码.
	 * 
	 * @param employeecode
	 *            用户编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 用户编码.
	 * 
	 * @return 用户编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 签到时间.
	 * 
	 * @param signintime
	 *            签到时间
	 */
	public void setSignintime(Date signintime) {
		this.signintime = signintime;
	}

	/**
	 * Get the 签到时间.
	 * 
	 * @return 签到时间
	 */
	public Date getSignintime() {
		return this.signintime;
	}

	/**
	 * Set the 充值金额.
	 * 
	 * @param depositamount
	 *            充值金额
	 */
	public void setDepositamount(Double depositamount) {
		this.depositamount = depositamount;
	}

	/**
	 * Get the 充值金额.
	 * 
	 * @return 充值金额
	 */
	public Double getDepositamount() {
		return this.depositamount;
	}

	/**
	 * Set the 打码金额.
	 * 
	 * @param betamount
	 *            打码金额
	 */
	public void setBetamount(Double betamount) {
		this.betamount = betamount;
	}

	/**
	 * Get the 打码金额.
	 * 
	 * @return 打码金额
	 */
	public Double getBetamount() {
		return this.betamount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rafflesignincode == null) ? 0 : rafflesignincode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActivityRaffleSignin other = (ActivityRaffleSignin) obj;
		if (rafflesignincode == null) {
			if (other.rafflesignincode != null) {
				return false;
			}
		} else if (!rafflesignincode.equals(other.rafflesignincode)) {
			return false;
		}
		return true;
	}

}
