package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of agent_site_contact.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AgentSiteContact implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer id;

	/** 站点编码. */
	private Integer domaincode;

	/** QQ . */
	private String qq;

	/** Skype. */
	private String skype;

	/** 微信. */
	private String vchat;

	/** 邮箱. */
	private String email;
	
	/** 手机号码 */
	private String phone;
	
	/** 唯一加密编码 */
	private String sign;
	
	/** 唯一加密编码 */
	private String sign1;

	/**
	 * Constructor.
	 */
	public AgentSiteContact() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param id
	 *            主键
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 站点编码.
	 * 
	 * @param domaincode
	 *            站点编码
	 */
	public void setDomaincode(Integer domaincode) {
		this.domaincode = domaincode;
	}

	/**
	 * Get the 站点编码.
	 * 
	 * @return 站点编码
	 */
	public Integer getDomaincode() {
		return this.domaincode;
	}

	/**
	 * Set the QQ .
	 * 
	 * @param qq
	 *            QQ 
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * Get the QQ .
	 * 
	 * @return QQ 
	 */
	public String getQq() {
		return this.qq;
	}

	/**
	 * Set the Skype.
	 * 
	 * @param skype
	 *            Skype
	 */
	public void setSkype(String skype) {
		this.skype = skype;
	}

	/**
	 * Get the Skype.
	 * 
	 * @return Skype
	 */
	public String getSkype() {
		return this.skype;
	}

	/**
	 * Set the 微信.
	 * 
	 * @param vchat
	 *            微信
	 */
	public void setVchat(String vchat) {
		this.vchat = vchat;
	}

	/**
	 * Get the 微信.
	 * 
	 * @return 微信
	 */
	public String getVchat() {
		return this.vchat;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getSign1() {
		return sign1;
	}

	public void setSign1(String sign1) {
		this.sign1 = sign1;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AgentSiteContact other = (AgentSiteContact) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
