package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of bank.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Bank implements Serializable,Comparable<Bank>,Cloneable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 银行代码. */
	private String bankcode;

	/** 银行名称. */
	private String bankname;

	/** 银行LOGO. */
	private String banklogo;

	/** 银行URL. */
	private String bankurl;

	/** 排序. */
	private Integer displayorder;

	/**
	 * Constructor.
	 */
	public Bank() {
	}

	/**
	 * Set the 银行代码.
	 * 
	 * @param bankcode
	 *            银行代码
	 */
	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	/**
	 * Get the 银行代码.
	 * 
	 * @return 银行代码
	 */
	public String getBankcode() {
		return this.bankcode;
	}

	/**
	 * Set the 银行名称.
	 * 
	 * @param bankname
	 *            银行名称
	 */
	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	/**
	 * Get the 银行名称.
	 * 
	 * @return 银行名称
	 */
	public String getBankname() {
		return this.bankname;
	}

	/**
	 * Set the 银行LOGO.
	 * 
	 * @param banklogo
	 *            银行LOGO
	 */
	public void setBanklogo(String banklogo) {
		this.banklogo = banklogo;
	}

	/**
	 * Get the 银行LOGO.
	 * 
	 * @return 银行LOGO
	 */
	public String getBanklogo() {
		return this.banklogo;
	}

	/**
	 * Set the 银行URL.
	 * 
	 * @param bankurl
	 *            银行URL
	 */
	public void setBankurl(String bankurl) {
		this.bankurl = bankurl;
	}

	/**
	 * Get the 银行URL.
	 * 
	 * @return 银行URL
	 */
	public String getBankurl() {
		return this.bankurl;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param displayorder
	 *            排序
	 */
	public void setDisplayorder(Integer displayorder) {
		this.displayorder = displayorder;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Integer getDisplayorder() {
		return this.displayorder;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bankcode == null) ? 0 : bankcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Bank other = (Bank) obj;
		if (bankcode == null) {
			if (other.bankcode != null) {
				return false;
			}
		} else if (!bankcode.equals(other.bankcode)) {
			return false;
		}
		return true;
	}

	@Override
	public int compareTo(Bank o) {
		return this.displayorder.compareTo(o.displayorder);
	}
	
	@Override
	public Bank clone() throws CloneNotSupportedException {
		return (Bank)super.clone();
	}

}
