package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_bbin.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqBbin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 注单号码. */
	private String bbinWagersId;
	
	/** 企业编码 */
	private String enterprisecode;

	/** brandcode. */
	private String brandcode;
	
	/** 用户编码 */
	private String employeecode;
	
	/*** 上级编码 */
    private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 帐号. */
	private String bbinUserName;

	/** 下注时间. */
	private Date bbinWagersDate;

	//投注内容
	private String bbinWagerDetail;
	/** 局号. */
	private String bbinSerialId;

	/** 场次. */
	private String bbinRoundNo;

	/** 游戏种类. */
	private String bbinGameType;

	/** 桌号. */
	private String bbinGameCode;

	/** 开牌结果. */
	private String bbinResult;

	/** 注单结果-1：注销、0：未结算. */
	private String bbinResultType;

	/** 结果牌. */
	private String bbinCard;

	/** 下注金额. */
	private Double bbinBetAmount;

	/** 派彩金额. */
	private Double bbinPayoff;

	/** 币别. */
	private String bbinCurrency;

	/** 与人民币的汇率. */
	private Double bbinExchangeRate;

	/** 会员有效投注额. */
	private Double bbinCommissionable;

	/** 退水. */
	private String bbinCommission;

	/** 1.行动装置下单：M 1-1.ios手机：MI1 1-2.ios平板：MI2 1-3.Android手机：MA1 1-4.Android平板：MA2 2.计算机下单：P. */
	private String bbinOrigin;

	/** 注单变更时间. */
	private String bbinModifiedDate;

	/** Y：已派彩、N：未派彩. */
	private String bbinIsPaid;

	/** 帐务时间. */
	private String bbinOrderDate;

	/** bbin_UPTIME. */
	private String bbinUptime;

	/** 平台更新时间. */
	private Date bbinCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqBbin() {
	}

	/**
	 * Set the 注单号码.
	 * 
	 * @param bbinWagersId
	 *            注单号码
	 */
	public void setBbinWagersId(String bbinWagersId) {
		this.bbinWagersId = bbinWagersId;
	}

	/**
	 * Get the 注单号码.
	 * 
	 * @return 注单号码
	 */
	public String getBbinWagersId() {
		return this.bbinWagersId;
	}

	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Set the brandcode.
	 * 
	 * @param brandcode
	 *            brandcode
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the brandcode.
	 * 
	 * @return brandcode
	 */
	public String getBrandcode() {
		return this.brandcode;
	}
	
	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}


	/**
	 * Get the parentemployeecode.
	 * 
	 * @return parentemployeecode
	 */
	public String getParentemployeecode() {
		return parentemployeecode;
	}

	/**
	 * Set the parentemployeecode.
	 * 
	 * @param parentemployeecode
	 *            parentemployeecode
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}
	
	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Set the 帐号.
	 * 
	 * @param bbinUserName
	 *            帐号
	 */
	public void setBbinUserName(String bbinUserName) {
		this.bbinUserName = bbinUserName;
	}

	/**
	 * Get the 帐号.
	 * 
	 * @return 帐号
	 */
	public String getBbinUserName() {
		return this.bbinUserName;
	}

	/**
	 * Set the 下注时间.
	 * 
	 * @param bbinWagersDate
	 *            下注时间
	 */
	public void setBbinWagersDate(Date bbinWagersDate) {
		this.bbinWagersDate = bbinWagersDate;
	}

	/**
	 * Get the 下注时间.
	 * 
	 * @return 下注时间
	 */
	public Date getBbinWagersDate() {
		return this.bbinWagersDate;
	}

	/**
	 * Set the 局号.
	 * 
	 * @param bbinSerialId
	 *            局号
	 */
	public void setBbinSerialId(String bbinSerialId) {
		this.bbinSerialId = bbinSerialId;
	}

	/**
	 * Get the 局号.
	 * 
	 * @return 局号
	 */
	public String getBbinSerialId() {
		return this.bbinSerialId;
	}

	/**
	 * Set the 场次.
	 * 
	 * @param bbinRoundNo
	 *            场次
	 */
	public void setBbinRoundNo(String bbinRoundNo) {
		this.bbinRoundNo = bbinRoundNo;
	}

	/**
	 * Get the 场次.
	 * 
	 * @return 场次
	 */
	public String getBbinRoundNo() {
		return this.bbinRoundNo;
	}

	/**
	 * Set the 游戏种类.
	 * 
	 * @param bbinGameType
	 *            游戏种类
	 */
	public void setBbinGameType(String bbinGameType) {
		this.bbinGameType = bbinGameType;
	}

	/**
	 * Get the 游戏种类.
	 * 
	 * @return 游戏种类
	 */
	public String getBbinGameType() {
		return this.bbinGameType;
	}

	/**
	 * Set the 桌号.
	 * 
	 * @param bbinGameCode
	 *            桌号
	 */
	public void setBbinGameCode(String bbinGameCode) {
		this.bbinGameCode = bbinGameCode;
	}

	/**
	 * Get the 桌号.
	 * 
	 * @return 桌号
	 */
	public String getBbinGameCode() {
		return this.bbinGameCode;
	}

	/**
	 * Set the 开牌结果.
	 * 
	 * @param bbinResult
	 *            开牌结果
	 */
	public void setBbinResult(String bbinResult) {
		this.bbinResult = bbinResult;
	}

	/**
	 * Get the 开牌结果.
	 * 
	 * @return 开牌结果
	 */
	public String getBbinResult() {
		return this.bbinResult;
	}

	/**
	 * Set the 注单结果-1：注销、0：未结算.
	 * 
	 * @param bbinResultType
	 *            注单结果-1：注销、0：未结算
	 */
	public void setBbinResultType(String bbinResultType) {
		this.bbinResultType = bbinResultType;
	}

	/**
	 * Get the 注单结果-1：注销、0：未结算.
	 * 
	 * @return 注单结果-1：注销、0：未结算
	 */
	public String getBbinResultType() {
		return this.bbinResultType;
	}

	/**
	 * Set the 结果牌.
	 * 
	 * @param bbinCard
	 *            结果牌
	 */
	public void setBbinCard(String bbinCard) {
		this.bbinCard = bbinCard;
	}

	/**
	 * Get the 结果牌.
	 * 
	 * @return 结果牌
	 */
	public String getBbinCard() {
		return this.bbinCard;
	}

	/**
	 * Set the 下注金额.
	 * 
	 * @param bbinBetAmount
	 *            下注金额
	 */
	public void setBbinBetAmount(Double bbinBetAmount) {
		this.bbinBetAmount = bbinBetAmount;
	}

	/**
	 * Get the 下注金额.
	 * 
	 * @return 下注金额
	 */
	public Double getBbinBetAmount() {
		return this.bbinBetAmount;
	}

	/**
	 * Set the 派彩金额.
	 * 
	 * @param bbinPayoff
	 *            派彩金额
	 */
	public void setBbinPayoff(Double bbinPayoff) {
		this.bbinPayoff = bbinPayoff;
	}

	/**
	 * Get the 派彩金额.
	 * 
	 * @return 派彩金额
	 */
	public Double getBbinPayoff() {
		return this.bbinPayoff;
	}

	/**
	 * Set the 币别.
	 * 
	 * @param bbinCurrency
	 *            币别
	 */
	public void setBbinCurrency(String bbinCurrency) {
		this.bbinCurrency = bbinCurrency;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * Get the 币别.
	 * 
	 * @return 币别
	 */
	public String getBbinCurrency() {
		return this.bbinCurrency;
	}

	/**
	 * Set the 与人民币的汇率.
	 * 
	 * @param bbinExchangeRate
	 *            与人民币的汇率
	 */
	public void setBbinExchangeRate(Double bbinExchangeRate) {
		this.bbinExchangeRate = bbinExchangeRate;
	}

	/**
	 * Get the 与人民币的汇率.
	 * 
	 * @return 与人民币的汇率
	 */
	public Double getBbinExchangeRate() {
		return this.bbinExchangeRate;
	}

	/**
	 * Set the 会员有效投注额.
	 * 
	 * @param bbinCommissionable
	 *            会员有效投注额
	 */
	public void setBbinCommissionable(Double bbinCommissionable) {
		this.bbinCommissionable = bbinCommissionable;
	}

	/**
	 * Get the 会员有效投注额.
	 * 
	 * @return 会员有效投注额
	 */
	public Double getBbinCommissionable() {
		return this.bbinCommissionable;
	}

	/**
	 * Set the 退水.
	 * 
	 * @param bbinCommission
	 *            退水
	 */
	public void setBbinCommission(String bbinCommission) {
		this.bbinCommission = bbinCommission;
	}

	/**
	 * Get the 退水.
	 * 
	 * @return 退水
	 */
	public String getBbinCommission() {
		return this.bbinCommission;
	}

	/**
	 * Set the 1.行动装置下单：M 1-1.ios手机：MI1 1-2.ios平板：MI2 1-3.Android手机：MA1 1-4.Android平板：MA2 2.计算机下单：P.
	 * 
	 * @param bbinOrigin
	 *            1.行动装置下单：M 1-1.ios手机：MI1 1-2.ios平板：MI2 1-3.Android手机：MA1 1-4.Android平板：MA2 2.计算机下单：P
	 */
	public void setBbinOrigin(String bbinOrigin) {
		this.bbinOrigin = bbinOrigin;
	}

	/**
	 * Get the 1.行动装置下单：M 1-1.ios手机：MI1 1-2.ios平板：MI2 1-3.Android手机：MA1 1-4.Android平板：MA2 2.计算机下单：P.
	 * 
	 * @return 1.行动装置下单：M 1-1.ios手机：MI1 1-2.ios平板：MI2 1-3.Android手机：MA1 1-4.Android平板：MA2 2.计算机下单：P
	 */
	public String getBbinOrigin() {
		return this.bbinOrigin;
	}

	/**
	 * Set the 注单变更时间.
	 * 
	 * @param bbinModifiedDate
	 *            注单变更时间
	 */
	public void setBbinModifiedDate(String bbinModifiedDate) {
		this.bbinModifiedDate = bbinModifiedDate;
	}

	/**
	 * Get the 注单变更时间.
	 * 
	 * @return 注单变更时间
	 */
	public String getBbinModifiedDate() {
		return this.bbinModifiedDate;
	}

	/**
	 * Set the Y：已派彩、N：未派彩.
	 * 
	 * @param bbinIsPaid
	 *            Y：已派彩、N：未派彩
	 */
	public void setBbinIsPaid(String bbinIsPaid) {
		this.bbinIsPaid = bbinIsPaid;
	}

	/**
	 * Get the Y：已派彩、N：未派彩.
	 * 
	 * @return Y：已派彩、N：未派彩
	 */
	public String getBbinIsPaid() {
		return this.bbinIsPaid;
	}

	/**
	 * Set the 帐务时间.
	 * 
	 * @param bbinOrderDate
	 *            帐务时间
	 */
	public void setBbinOrderDate(String bbinOrderDate) {
		this.bbinOrderDate = bbinOrderDate;
	}

	/**
	 * Get the 帐务时间.
	 * 
	 * @return 帐务时间
	 */
	public String getBbinOrderDate() {
		return this.bbinOrderDate;
	}

	/**
	 * Set the bbin_UPTIME.
	 * 
	 * @param bbinUptime
	 *            bbin_UPTIME
	 */
	public void setBbinUptime(String bbinUptime) {
		this.bbinUptime = bbinUptime;
	}

	/**
	 * Get the bbin_UPTIME.
	 * 
	 * @return bbin_UPTIME
	 */
	public String getBbinUptime() {
		return this.bbinUptime;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param bbinCreatetime
	 *            平台更新时间
	 */
	public void setBbinCreatetime(Date bbinCreatetime) {
		this.bbinCreatetime = bbinCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getBbinCreatetime() {
		return this.bbinCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bbinWagersId == null) ? 0 : bbinWagersId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqBbin other = (BettingHqBbin) obj;
		if (bbinWagersId == null) {
			if (other.bbinWagersId != null) {
				return false;
			}
		} else if (!bbinWagersId.equals(other.bbinWagersId)) {
			return false;
		}
		return true;
	}

	public String getBbinWagerDetail() {
		return bbinWagerDetail;
	}

	public void setBbinWagerDetail(String bbinWagerDetail) {
		this.bbinWagerDetail = bbinWagerDetail;
	}

}
