package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_pt.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqPt implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 游戏编号. */
	private String ptGamecode;
	
	/** 企业编码 */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;
	
	/** 用户编码 */
	private String employeecode;
	
	private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 游戏类型. */
	private String ptGametype;

	/** 游戏id. */
	private String ptGameid;

	/** 游戏名称. */
	private String ptGamename;

	/** 用户名. */
	private String ptUsername;

	/** 窗口代码. */
	private String ptWindowcode;

	/** 投注额. */
	private Double ptBet;

	/** 赢. */
	private Double ptWin;

	/** 余额. */
	private Double ptBalance;

	/** 游戏时间. */
	private Date ptGamedate;

	/** 游戏信息. */
	private String ptInfo;

	/** sessionID. */
	private String ptSessionid;

	/** 逐步下注. */
	private String ptProgressivebet;

	/** 进步的胜利. */
	private String ptProgressivewin;

	/** 最近赌注. */
	private String ptCurrentbet;

	/** 活网工作. */
	private String ptLivenetwork;

	/** 序号. */
	private String ptRnum;

	/** 平台更新时间. */
	private Date ptCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqPt() {
	}

	/**
	 * Set the 游戏编号.
	 * 
	 * @param ptGamecode
	 *            游戏编号
	 */
	public void setPtGamecode(String ptGamecode) {
		this.ptGamecode = ptGamecode;
	}

	/**
	 * Get the 游戏编号.
	 * 
	 * @return 游戏编号
	 */
	public String getPtGamecode() {
		return this.ptGamecode;
	}
	
	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}


	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}
	
	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}


	/**
	 * Set the 游戏类型.
	 * 
	 * @param ptGametype
	 *            游戏类型
	 */
	public void setPtGametype(String ptGametype) {
		this.ptGametype = ptGametype;
	}

	/**
	 * Get the 游戏类型.
	 * 
	 * @return 游戏类型
	 */
	public String getPtGametype() {
		return this.ptGametype;
	}

	/**
	 * Set the 游戏id.
	 * 
	 * @param ptGameid
	 *            游戏id
	 */
	public void setPtGameid(String ptGameid) {
		this.ptGameid = ptGameid;
	}

	/**
	 * Get the 游戏id.
	 * 
	 * @return 游戏id
	 */
	public String getPtGameid() {
		return this.ptGameid;
	}

	/**
	 * Set the 游戏名称.
	 * 
	 * @param ptGamename
	 *            游戏名称
	 */
	public void setPtGamename(String ptGamename) {
		this.ptGamename = ptGamename;
	}

	/**
	 * Get the 游戏名称.
	 * 
	 * @return 游戏名称
	 */
	public String getPtGamename() {
		return this.ptGamename;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param ptUsername
	 *            用户名
	 */
	public void setPtUsername(String ptUsername) {
		this.ptUsername = ptUsername;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getPtUsername() {
		return this.ptUsername;
	}

	/**
	 * Set the 窗口代码.
	 * 
	 * @param ptWindowcode
	 *            窗口代码
	 */
	public void setPtWindowcode(String ptWindowcode) {
		this.ptWindowcode = ptWindowcode;
	}

	/**
	 * Get the 窗口代码.
	 * 
	 * @return 窗口代码
	 */
	public String getPtWindowcode() {
		return this.ptWindowcode;
	}

	/**
	 * Set the 投注额.
	 * 
	 * @param ptBet
	 *            投注额
	 */
	public void setPtBet(Double ptBet) {
		this.ptBet = ptBet;
	}

	/**
	 * Get the 投注额.
	 * 
	 * @return 投注额
	 */
	public Double getPtBet() {
		return this.ptBet;
	}

	/**
	 * Set the 赢.
	 * 
	 * @param ptWin
	 *            赢
	 */
	public void setPtWin(Double ptWin) {
		this.ptWin = ptWin;
	}

	/**
	 * Get the 赢.
	 * 
	 * @return 赢
	 */
	public Double getPtWin() {
		return this.ptWin;
	}

	/**
	 * Set the 余额.
	 * 
	 * @param ptBalance
	 *            余额
	 */
	public void setPtBalance(Double ptBalance) {
		this.ptBalance = ptBalance;
	}

	/**
	 * Get the 余额.
	 * 
	 * @return 余额
	 */
	public Double getPtBalance() {
		return this.ptBalance;
	}

	/**
	 * Set the 游戏时间.
	 * 
	 * @param ptGamedate
	 *            游戏时间
	 */
	public void setPtGamedate(Date ptGamedate) {
		this.ptGamedate = ptGamedate;
	}

	/**
	 * Get the 游戏时间.
	 * 
	 * @return 游戏时间
	 */
	public Date getPtGamedate() {
		return this.ptGamedate;
	}

	/**
	 * Set the 游戏信息.
	 * 
	 * @param ptInfo
	 *            游戏信息
	 */
	public void setPtInfo(String ptInfo) {
		this.ptInfo = ptInfo;
	}

	/**
	 * Get the 游戏信息.
	 * 
	 * @return 游戏信息
	 */
	public String getPtInfo() {
		return this.ptInfo;
	}

	/**
	 * Set the sessionID.
	 * 
	 * @param ptSessionid
	 *            sessionID
	 */
	public void setPtSessionid(String ptSessionid) {
		this.ptSessionid = ptSessionid;
	}

	/**
	 * Get the sessionID.
	 * 
	 * @return sessionID
	 */
	public String getPtSessionid() {
		return this.ptSessionid;
	}

	/**
	 * Set the 逐步下注.
	 * 
	 * @param ptProgressivebet
	 *            逐步下注
	 */
	public void setPtProgressivebet(String ptProgressivebet) {
		this.ptProgressivebet = ptProgressivebet;
	}

	/**
	 * Get the 逐步下注.
	 * 
	 * @return 逐步下注
	 */
	public String getPtProgressivebet() {
		return this.ptProgressivebet;
	}

	/**
	 * Set the 进步的胜利.
	 * 
	 * @param ptProgressivewin
	 *            进步的胜利
	 */
	public void setPtProgressivewin(String ptProgressivewin) {
		this.ptProgressivewin = ptProgressivewin;
	}

	/**
	 * Get the 进步的胜利.
	 * 
	 * @return 进步的胜利
	 */
	public String getPtProgressivewin() {
		return this.ptProgressivewin;
	}

	/**
	 * Set the 最近赌注.
	 * 
	 * @param ptCurrentbet
	 *            最近赌注
	 */
	public void setPtCurrentbet(String ptCurrentbet) {
		this.ptCurrentbet = ptCurrentbet;
	}

	/**
	 * Get the 最近赌注.
	 * 
	 * @return 最近赌注
	 */
	public String getPtCurrentbet() {
		return this.ptCurrentbet;
	}

	/**
	 * Set the 活网工作.
	 * 
	 * @param ptLivenetwork
	 *            活网工作
	 */
	public void setPtLivenetwork(String ptLivenetwork) {
		this.ptLivenetwork = ptLivenetwork;
	}

	/**
	 * Get the 活网工作.
	 * 
	 * @return 活网工作
	 */
	public String getPtLivenetwork() {
		return this.ptLivenetwork;
	}

	/**
	 * Set the 序号.
	 * 
	 * @param ptRnum
	 *            序号
	 */
	public void setPtRnum(String ptRnum) {
		this.ptRnum = ptRnum;
	}

	/**
	 * Get the 序号.
	 * 
	 * @return 序号
	 */
	public String getPtRnum() {
		return this.ptRnum;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param ptCreatetime
	 *            平台更新时间
	 */
	public void setPtCreatetime(Date ptCreatetime) {
		this.ptCreatetime = ptCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getPtCreatetime() {
		return this.ptCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public String getParentemployeecode() {
		return parentemployeecode;
	}

	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ptGamecode == null) ? 0 : ptGamecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqPt other = (BettingHqPt) obj;
		if (ptGamecode == null) {
			if (other.ptGamecode != null) {
				return false;
			}
		} else if (!ptGamecode.equals(other.ptGamecode)) {
			return false;
		}
		return true;
	}

}
