package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_og_ag.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqOgAg implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 唯一ID. */
	private String aoiProductId;
	
	/** 企业编码 */
	private String enterprisecode;

	/** brandcode. */
	private String brandcode;
	
	/** 用户编码 */
	private String employeecode;
	
	/*** 上级编码 */
    private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 用户名. */
	private String aoiUserName;

	/** 游戏结果. */
	private String aoiGameRecordId;

	/** 单号. */
	private String aoiOrderNumber;

	/** 桌号. */
	private String aoiTableId;

	/** 局号. */
	private String aoiStage;

	/** 靴号. */
	private String aoiInning;

	/** 游戏类型. */
	private String aoiGameNameId;

	/** 投注类型. */
	private String aoiGameBettingKind;

	/** 番摊,轮盘,骰宝的投注区. */
	private String aoiGameBettingContent;

	/** 游戏结果类型. */
	private String aoiResultType;

	/** 投注金额. */
	private Double aoiBettingAmount;

	/** 赔率. */
	private String aoiCompensateRate;

	/** 输赢金额. */
	private Double aoiWinLoseAmount;

	/** 余额. */
	private Double aoiBalance;

	/** 交易时间. */
	private Date aoiAddTime;

	/** 供应商Id. */
	private String aoiVendorId;

	/** 有效投注额. */
	private Double aoiValidAmount;

	/** aoi_PlatformID. */
	private String aoiPlatformid;

	/** 平台更新时间. */
	private Date aoiCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqOgAg() {
	}

	/**
	 * Set the 唯一ID.
	 * 
	 * @param aoiProductId
	 *            唯一ID
	 */
	public void setAoiProductId(String aoiProductId) {
		this.aoiProductId = aoiProductId;
	}

	/**
	 * Get the 唯一ID.
	 * 
	 * @return 唯一ID
	 */
	public String getAoiProductId() {
		return this.aoiProductId;
	}
	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Set the brandcode.
	 * 
	 * @param brandcode
	 *            brandcode
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the brandcode.
	 * 
	 * @return brandcode
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}
	
	/**
	 * Get the parentemployeecode.
	 * 
	 * @return parentemployeecode
	 */
	public String getParentemployeecode() {
		return parentemployeecode;
	}

	/**
	 * Set the parentemployeecode.
	 * 
	 * @param parentemployeecode
	 *            parentemployeecode
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param aoiUserName
	 *            用户名
	 */
	public void setAoiUserName(String aoiUserName) {
		this.aoiUserName = aoiUserName;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getAoiUserName() {
		return this.aoiUserName;
	}

	/**
	 * Set the 游戏结果.
	 * 
	 * @param aoiGameRecordId
	 *            游戏结果
	 */
	public void setAoiGameRecordId(String aoiGameRecordId) {
		this.aoiGameRecordId = aoiGameRecordId;
	}

	/**
	 * Get the 游戏结果.
	 * 
	 * @return 游戏结果
	 */
	public String getAoiGameRecordId() {
		return this.aoiGameRecordId;
	}

	/**
	 * Set the 单号.
	 * 
	 * @param aoiOrderNumber
	 *            单号
	 */
	public void setAoiOrderNumber(String aoiOrderNumber) {
		this.aoiOrderNumber = aoiOrderNumber;
	}

	/**
	 * Get the 单号.
	 * 
	 * @return 单号
	 */
	public String getAoiOrderNumber() {
		return this.aoiOrderNumber;
	}

	/**
	 * Set the 桌号.
	 * 
	 * @param aoiTableId
	 *            桌号
	 */
	public void setAoiTableId(String aoiTableId) {
		this.aoiTableId = aoiTableId;
	}

	/**
	 * Get the 桌号.
	 * 
	 * @return 桌号
	 */
	public String getAoiTableId() {
		return this.aoiTableId;
	}

	/**
	 * Set the 局号.
	 * 
	 * @param aoiStage
	 *            局号
	 */
	public void setAoiStage(String aoiStage) {
		this.aoiStage = aoiStage;
	}

	/**
	 * Get the 局号.
	 * 
	 * @return 局号
	 */
	public String getAoiStage() {
		return this.aoiStage;
	}

	/**
	 * Set the 靴号.
	 * 
	 * @param aoiInning
	 *            靴号
	 */
	public void setAoiInning(String aoiInning) {
		this.aoiInning = aoiInning;
	}

	/**
	 * Get the 靴号.
	 * 
	 * @return 靴号
	 */
	public String getAoiInning() {
		return this.aoiInning;
	}

	/**
	 * Set the 游戏类型.
	 * 
	 * @param aoiGameNameId
	 *            游戏类型
	 */
	public void setAoiGameNameId(String aoiGameNameId) {
		this.aoiGameNameId = aoiGameNameId;
	}

	/**
	 * Get the 游戏类型.
	 * 
	 * @return 游戏类型
	 */
	public String getAoiGameNameId() {
		return this.aoiGameNameId;
	}

	/**
	 * Set the 投注类型.
	 * 
	 * @param aoiGameBettingKind
	 *            投注类型
	 */
	public void setAoiGameBettingKind(String aoiGameBettingKind) {
		this.aoiGameBettingKind = aoiGameBettingKind;
	}

	/**
	 * Get the 投注类型.
	 * 
	 * @return 投注类型
	 */
	public String getAoiGameBettingKind() {
		return this.aoiGameBettingKind;
	}

	/**
	 * Set the 番摊,轮盘,骰宝的投注区.
	 * 
	 * @param aoiGameBettingContent
	 *            番摊,轮盘,骰宝的投注区
	 */
	public void setAoiGameBettingContent(String aoiGameBettingContent) {
		this.aoiGameBettingContent = aoiGameBettingContent;
	}

	/**
	 * Get the 番摊,轮盘,骰宝的投注区.
	 * 
	 * @return 番摊,轮盘,骰宝的投注区
	 */
	public String getAoiGameBettingContent() {
		return this.aoiGameBettingContent;
	}

	/**
	 * Set the 游戏结果类型.
	 * 
	 * @param aoiResultType
	 *            游戏结果类型
	 */
	public void setAoiResultType(String aoiResultType) {
		this.aoiResultType = aoiResultType;
	}

	/**
	 * Get the 游戏结果类型.
	 * 
	 * @return 游戏结果类型
	 */
	public String getAoiResultType() {
		return this.aoiResultType;
	}

	/**
	 * Set the 投注金额.
	 * 
	 * @param aoiBettingAmount
	 *            投注金额
	 */
	public void setAoiBettingAmount(Double aoiBettingAmount) {
		this.aoiBettingAmount = aoiBettingAmount;
	}

	/**
	 * Get the 投注金额.
	 * 
	 * @return 投注金额
	 */
	public Double getAoiBettingAmount() {
		return this.aoiBettingAmount;
	}

	/**
	 * Set the 赔率.
	 * 
	 * @param aoiCompensateRate
	 *            赔率
	 */
	public void setAoiCompensateRate(String aoiCompensateRate) {
		this.aoiCompensateRate = aoiCompensateRate;
	}

	/**
	 * Get the 赔率.
	 * 
	 * @return 赔率
	 */
	public String getAoiCompensateRate() {
		return this.aoiCompensateRate;
	}

	/**
	 * Set the 输赢金额.
	 * 
	 * @param aoiWinLoseAmount
	 *            输赢金额
	 */
	public void setAoiWinLoseAmount(Double aoiWinLoseAmount) {
		this.aoiWinLoseAmount = aoiWinLoseAmount;
	}

	/**
	 * Get the 输赢金额.
	 * 
	 * @return 输赢金额
	 */
	public Double getAoiWinLoseAmount() {
		return this.aoiWinLoseAmount;
	}

	/**
	 * Set the 余额.
	 * 
	 * @param aoiBalance
	 *            余额
	 */
	public void setAoiBalance(Double aoiBalance) {
		this.aoiBalance = aoiBalance;
	}

	/**
	 * Get the 余额.
	 * 
	 * @return 余额
	 */
	public Double getAoiBalance() {
		return this.aoiBalance;
	}

	/**
	 * Set the 交易时间.
	 * 
	 * @param aoiAddTime
	 *            交易时间
	 */
	public void setAoiAddTime(Date aoiAddTime) {
		this.aoiAddTime = aoiAddTime;
	}

	/**
	 * Get the 交易时间.
	 * 
	 * @return 交易时间
	 */
	public Date getAoiAddTime() {
		return this.aoiAddTime;
	}

	/**
	 * Set the 供应商Id.
	 * 
	 * @param aoiVendorId
	 *            供应商Id
	 */
	public void setAoiVendorId(String aoiVendorId) {
		this.aoiVendorId = aoiVendorId;
	}

	/**
	 * Get the 供应商Id.
	 * 
	 * @return 供应商Id
	 */
	public String getAoiVendorId() {
		return this.aoiVendorId;
	}

	/**
	 * Set the 有效投注额.
	 * 
	 * @param aoiValidAmount
	 *            有效投注额
	 */
	public void setAoiValidAmount(Double aoiValidAmount) {
		this.aoiValidAmount = aoiValidAmount;
	}

	/**
	 * Get the 有效投注额.
	 * 
	 * @return 有效投注额
	 */
	public Double getAoiValidAmount() {
		return this.aoiValidAmount;
	}

	/**
	 * Set the aoi_PlatformID.
	 * 
	 * @param aoiPlatformid
	 *            aoi_PlatformID
	 */
	public void setAoiPlatformid(String aoiPlatformid) {
		this.aoiPlatformid = aoiPlatformid;
	}

	/**
	 * Get the aoi_PlatformID.
	 * 
	 * @return aoi_PlatformID
	 */
	public String getAoiPlatformid() {
		return this.aoiPlatformid;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param aoiCreatetime
	 *            平台更新时间
	 */
	public void setAoiCreatetime(Date aoiCreatetime) {
		this.aoiCreatetime = aoiCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getAoiCreatetime() {
		return this.aoiCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aoiProductId == null) ? 0 : aoiProductId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqOgAg other = (BettingHqOgAg) obj;
		if (aoiProductId == null) {
			if (other.aoiProductId != null) {
				return false;
			}
		} else if (!aoiProductId.equals(other.aoiProductId)) {
			return false;
		}
		return true;
	}

}
