package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_xcp.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqXcp implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 投注id. */
	private String xcpProjectid;
	
	/** 企业编码 */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;
	
	/** 用户编码 */
	private String employeecode;
	
	/*** 上级编码 */
    private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 返奖. */
	private Double xcpBonus;

	/** 奖金额. */
	private Double xcpPrize;

	/** 下注时间. */
	private Date xcpWritetime;

	/** 用户名. */
	private String xcpUsername;

	/** 下注内容. */
	private String xcpCode;

	/** 下注金额. */
	private Double xcpTotalprice;

	/** 是否中奖，0=未中间，1=中奖. */
	private String xcpIsgetprize;

	/** 派奖时间. */
	private Date xcpUpdatetime;

	/** 彩种，彩种编号参照附录. */
	private String xcpLotteryid;

	/** 奖期. */
	private String xcpIssue;

	/** 倍数. */
	private Double xcpCodetimes;

	/** 平台更新时间. */
	private Date xcpCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqXcp() {
	}

	/**
	 * Set the 投注id.
	 * 
	 * @param xcpProjectid
	 *            投注id
	 */
	public void setXcpProjectid(String xcpProjectid) {
		this.xcpProjectid = xcpProjectid;
	}

	/**
	 * Get the 投注id.
	 * 
	 * @return 投注id
	 */
	public String getXcpProjectid() {
		return this.xcpProjectid;
	}

	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	public String getParentemployeecode() {
		return parentemployeecode;
	}

	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}
	
	/**
	 * Set the 返奖.
	 * 
	 * @param xcpBonus
	 *            返奖
	 */
	public void setXcpBonus(Double xcpBonus) {
		this.xcpBonus = xcpBonus;
	}

	/**
	 * Get the 返奖.
	 * 
	 * @return 返奖
	 */
	public Double getXcpBonus() {
		return this.xcpBonus;
	}

	/**
	 * Set the 奖金额.
	 * 
	 * @param xcpPrize
	 *            奖金额
	 */
	public void setXcpPrize(Double xcpPrize) {
		this.xcpPrize = xcpPrize;
	}

	/**
	 * Get the 奖金额.
	 * 
	 * @return 奖金额
	 */
	public Double getXcpPrize() {
		return this.xcpPrize;
	}

	/**
	 * Set the 下注时间.
	 * 
	 * @param xcpWritetime
	 *            下注时间
	 */
	public void setXcpWritetime(Date xcpWritetime) {
		this.xcpWritetime = xcpWritetime;
	}

	/**
	 * Get the 下注时间.
	 * 
	 * @return 下注时间
	 */
	public Date getXcpWritetime() {
		return this.xcpWritetime;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param xcpUsername
	 *            用户名
	 */
	public void setXcpUsername(String xcpUsername) {
		this.xcpUsername = xcpUsername;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getXcpUsername() {
		return this.xcpUsername;
	}

	/**
	 * Set the 下注内容.
	 * 
	 * @param xcpCode
	 *            下注内容
	 */
	public void setXcpCode(String xcpCode) {
		this.xcpCode = xcpCode;
	}

	/**
	 * Get the 下注内容.
	 * 
	 * @return 下注内容
	 */
	public String getXcpCode() {
		return this.xcpCode;
	}

	/**
	 * Set the 下注金额.
	 * 
	 * @param xcpTotalprice
	 *            下注金额
	 */
	public void setXcpTotalprice(Double xcpTotalprice) {
		this.xcpTotalprice = xcpTotalprice;
	}

	/**
	 * Get the 下注金额.
	 * 
	 * @return 下注金额
	 */
	public Double getXcpTotalprice() {
		return this.xcpTotalprice;
	}

	/**
	 * Set the 是否中奖，0=未中间，1=中奖.
	 * 
	 * @param xcpIsgetprize
	 *            是否中奖，0=未中间，1=中奖
	 */
	public void setXcpIsgetprize(String xcpIsgetprize) {
		this.xcpIsgetprize = xcpIsgetprize;
	}

	/**
	 * Get the 是否中奖，0=未中间，1=中奖.
	 * 
	 * @return 是否中奖，0=未中间，1=中奖
	 */
	public String getXcpIsgetprize() {
		return this.xcpIsgetprize;
	}

	/**
	 * Set the 派奖时间.
	 * 
	 * @param xcpUpdatetime
	 *            派奖时间
	 */
	public void setXcpUpdatetime(Date xcpUpdatetime) {
		this.xcpUpdatetime = xcpUpdatetime;
	}

	/**
	 * Get the 派奖时间.
	 * 
	 * @return 派奖时间
	 */
	public Date getXcpUpdatetime() {
		return this.xcpUpdatetime;
	}

	/**
	 * Set the 彩种，彩种编号参照附录.
	 * 
	 * @param xcpLotteryid
	 *            彩种，彩种编号参照附录
	 */
	public void setXcpLotteryid(String xcpLotteryid) {
		this.xcpLotteryid = xcpLotteryid;
	}

	/**
	 * Get the 彩种，彩种编号参照附录.
	 * 
	 * @return 彩种，彩种编号参照附录
	 */
	public String getXcpLotteryid() {
		return this.xcpLotteryid;
	}

	/**
	 * Set the 奖期.
	 * 
	 * @param xcpIssue
	 *            奖期
	 */
	public void setXcpIssue(String xcpIssue) {
		this.xcpIssue = xcpIssue;
	}

	/**
	 * Get the 奖期.
	 * 
	 * @return 奖期
	 */
	public String getXcpIssue() {
		return this.xcpIssue;
	}

	/**
	 * Set the 倍数.
	 * 
	 * @param xcpCodetimes
	 *            倍数
	 */
	public void setXcpCodetimes(Double xcpCodetimes) {
		this.xcpCodetimes = xcpCodetimes;
	}

	/**
	 * Get the 倍数.
	 * 
	 * @return 倍数
	 */
	public Double getXcpCodetimes() {
		return this.xcpCodetimes;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param xcpCreatetime
	 *            平台更新时间
	 */
	public void setXcpCreatetime(Date xcpCreatetime) {
		this.xcpCreatetime = xcpCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getXcpCreatetime() {
		return this.xcpCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((xcpProjectid == null) ? 0 : xcpProjectid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqXcp other = (BettingHqXcp) obj;
		if (xcpProjectid == null) {
			if (other.xcpProjectid != null) {
				return false;
			}
		} else if (!xcpProjectid.equals(other.xcpProjectid)) {
			return false;
		}
		return true;
	}

}
