package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_yg_ag.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingYgAg implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 注单 ID. */
	private String betId;

	/** 企业编码. */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;

	/** 员工编码. */
	private String employeecode;

	/** 上级编码. */
	private String parentemployeecode;

	/** 登陆账号. */
	private String loginaccount;

	/** 游戏大类. */
	private String gamebigtype;

	/** 会员帐号. */
	private String user;

	/** 游戏 ID. */
	private String gameId;

	/** 游戏名称. */
	private String gameName;

	/** 下注金额. */
	private Double money;

	/** 备注，如游戏场景 ID，捕鱼王奖励，游戏局号等. */
	private String remarks;

	/** 下注时间. */
	private Date time;

	/** 输赢结果，正数为会员所赢的钱数，负数为会员输的钱. */
	private Double result;

	/** 有效下注金额. */
	private Double validMoney;

	/** 创建时间？. */
	private Date createtime;

	/**
	 * Constructor.
	 */
	public BettingYgAg() {
	}

	/**
	 * Set the 注单 ID.
	 * 
	 * @param betId
	 *            注单 ID
	 */
	public void setBetId(String betId) {
		this.betId = betId;
	}

	/**
	 * Get the 注单 ID.
	 * 
	 * @return 注单 ID
	 */
	public String getBetId() {
		return this.betId;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 上级编码.
	 * 
	 * @param parentemployeecode
	 *            上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 上级编码.
	 * 
	 * @return 上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 登陆账号.
	 * 
	 * @param loginaccount
	 *            登陆账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 登陆账号.
	 * 
	 * @return 登陆账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 游戏大类.
	 * 
	 * @param gamebigtype
	 *            游戏大类
	 */
	public void setGamebigtype(String gamebigtype) {
		this.gamebigtype = gamebigtype;
	}

	/**
	 * Get the 游戏大类.
	 * 
	 * @return 游戏大类
	 */
	public String getGamebigtype() {
		return this.gamebigtype;
	}

	/**
	 * Set the 会员帐号.
	 * 
	 * @param user
	 *            会员帐号
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * Get the 会员帐号.
	 * 
	 * @return 会员帐号
	 */
	public String getUser() {
		return this.user;
	}

	/**
	 * Set the 游戏 ID.
	 * 
	 * @param gameId
	 *            游戏 ID
	 */
	public void setGameId(String gameId) {
		this.gameId = gameId;
	}

	/**
	 * Get the 游戏 ID.
	 * 
	 * @return 游戏 ID
	 */
	public String getGameId() {
		return this.gameId;
	}

	/**
	 * Set the 游戏名称.
	 * 
	 * @param gameName
	 *            游戏名称
	 */
	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	/**
	 * Get the 游戏名称.
	 * 
	 * @return 游戏名称
	 */
	public String getGameName() {
		return this.gameName;
	}

	/**
	 * Set the 下注金额.
	 * 
	 * @param money
	 *            下注金额
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * Get the 下注金额.
	 * 
	 * @return 下注金额
	 */
	public Double getMoney() {
		return this.money;
	}

	/**
	 * Set the 备注，如游戏场景 ID，捕鱼王奖励，游戏局号等.
	 * 
	 * @param remarks
	 *            备注，如游戏场景 ID，捕鱼王奖励，游戏局号等
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Get the 备注，如游戏场景 ID，捕鱼王奖励，游戏局号等.
	 * 
	 * @return 备注，如游戏场景 ID，捕鱼王奖励，游戏局号等
	 */
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Set the 下注时间.
	 * 
	 * @param time
	 *            下注时间
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * Get the 下注时间.
	 * 
	 * @return 下注时间
	 */
	public Date getTime() {
		return this.time;
	}

	/**
	 * Set the 输赢结果，正数为会员所赢的钱数，负数为会员输的钱.
	 * 
	 * @param result
	 *            输赢结果，正数为会员所赢的钱数，负数为会员输的钱
	 */
	public void setResult(Double result) {
		this.result = result;
	}

	/**
	 * Get the 输赢结果，正数为会员所赢的钱数，负数为会员输的钱.
	 * 
	 * @return 输赢结果，正数为会员所赢的钱数，负数为会员输的钱
	 */
	public Double getResult() {
		return this.result;
	}

	/**
	 * Set the 有效下注金额.
	 * 
	 * @param validMoney
	 *            有效下注金额
	 */
	public void setValidMoney(Double validMoney) {
		this.validMoney = validMoney;
	}

	/**
	 * Get the 有效下注金额.
	 * 
	 * @return 有效下注金额
	 */
	public Double getValidMoney() {
		return this.validMoney;
	}

	/**
	 * Set the 创建时间？.
	 * 
	 * @param createtime
	 *            创建时间？
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间？.
	 * 
	 * @return 创建时间？
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((betId == null) ? 0 : betId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingYgAg other = (BettingYgAg) obj;
		if (betId == null) {
			if (other.betId != null) {
				return false;
			}
		} else if (!betId.equals(other.betId)) {
			return false;
		}
		return true;
	}

}
