package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_hq.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqHq implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 单号ID. */
	private String hqId;
	
	/** 企业编码 */
	private String enterprisecode;

	/** brandcode. */
	private String brandcode;
	
	/** 用户团队集合 */
	private String employeecodes;	
	
	/** 用户编码 */
	private String employeecode;
	
	/*** 上级编码 */
    private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 投注时间 */
	private Date hqDt;

	/** 游戏帐号. */
	private String hqNm;

	/** 游戏编号. */
	private String hqGm;

	/** 靴号. */
	private String hqBt;

	/** 局次. */
	private String hqRn;

	/** 厅号. */
	private String hqHl;

	/** 桌号. */
	private String hqTbl;

	/** 投注点. */
	private String hqPt;

	/** 下注金额. */
	private Double hqBet;

	/** 输赢金额 无负数 0为输掉投注金额. */
	private Double hqWin;

	/** 有效投注额. */
	private Double hqTm;

	/** 结果. */
	private String hqWer;

	/** 投注编号. */
	private String hqRec;

	/** 牌面. */
	private String hqCrd;

	/** 平台更新时间. */
	private Date hqCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqHq() {
	}

	/**
	 * Set the 单号ID.
	 * 
	 * @param hqId
	 *            单号ID
	 */
	public void setHqId(String hqId) {
		this.hqId = hqId;
	}

	/**
	 * Get the 单号ID.
	 * 
	 * @return 单号ID
	 */
	public String getHqId() {
		return this.hqId;
	}
	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Set the brandcode.
	 * 
	 * @param brandcode
	 *            brandcode
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the brandcode.
	 * 
	 * @return brandcode
	 */
	public String getBrandcode() {
		return this.brandcode;
	}
	
	public String getEmployeecodes() {
		return employeecodes;
	}

	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}
	
	/**
	 * Get the parentemployeecode.
	 * 
	 * @return parentemployeecode
	 */
	public String getParentemployeecode() {
		return parentemployeecode;
	}

	/**
	 * Set the parentemployeecode.
	 * 
	 * @param parentemployeecode
	 *            parentemployeecode
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Set the 桌号.
	 * 
	 * @param hqDt
	 *            桌号
	 */
	public void setHqDt(Date hqDt) {
		this.hqDt = hqDt;
	}

	/**
	 * Get the 桌号.
	 * 
	 * @return 桌号
	 */
	public Date getHqDt() {
		return this.hqDt;
	}

	/**
	 * Set the 游戏帐号.
	 * 
	 * @param hqNm
	 *            游戏帐号
	 */
	public void setHqNm(String hqNm) {
		this.hqNm = hqNm;
	}

	/**
	 * Get the 游戏帐号.
	 * 
	 * @return 游戏帐号
	 */
	public String getHqNm() {
		return this.hqNm;
	}

	/**
	 * Set the 游戏编号.
	 * 
	 * @param hqGm
	 *            游戏编号
	 */
	public void setHqGm(String hqGm) {
		this.hqGm = hqGm;
	}

	/**
	 * Get the 游戏编号.
	 * 
	 * @return 游戏编号
	 */
	public String getHqGm() {
		return this.hqGm;
	}

	/**
	 * Set the 靴号.
	 * 
	 * @param hqBt
	 *            靴号
	 */
	public void setHqBt(String hqBt) {
		this.hqBt = hqBt;
	}

	/**
	 * Get the 靴号.
	 * 
	 * @return 靴号
	 */
	public String getHqBt() {
		return this.hqBt;
	}

	/**
	 * Set the 局次.
	 * 
	 * @param hqRn
	 *            局次
	 */
	public void setHqRn(String hqRn) {
		this.hqRn = hqRn;
	}

	/**
	 * Get the 局次.
	 * 
	 * @return 局次
	 */
	public String getHqRn() {
		return this.hqRn;
	}

	/**
	 * Set the 厅号.
	 * 
	 * @param hqHl
	 *            厅号
	 */
	public void setHqHl(String hqHl) {
		this.hqHl = hqHl;
	}

	/**
	 * Get the 厅号.
	 * 
	 * @return 厅号
	 */
	public String getHqHl() {
		return this.hqHl;
	}

	/**
	 * Set the 桌号.
	 * 
	 * @param hqTbl
	 *            桌号
	 */
	public void setHqTbl(String hqTbl) {
		this.hqTbl = hqTbl;
	}

	/**
	 * Get the 桌号.
	 * 
	 * @return 桌号
	 */
	public String getHqTbl() {
		return this.hqTbl;
	}

	/**
	 * Set the 投注点.
	 * 
	 * @param hqPt
	 *            投注点
	 */
	public void setHqPt(String hqPt) {
		this.hqPt = hqPt;
	}

	/**
	 * Get the 投注点.
	 * 
	 * @return 投注点
	 */
	public String getHqPt() {
		return this.hqPt;
	}

	/**
	 * Set the 下注金额.
	 * 
	 * @param hqBet
	 *            下注金额
	 */
	public void setHqBet(Double hqBet) {
		this.hqBet = hqBet;
	}

	/**
	 * Get the 下注金额.
	 * 
	 * @return 下注金额
	 */
	public Double getHqBet() {
		return this.hqBet;
	}

	/**
	 * Set the 输赢金额 无负数 0为输掉投注金额.
	 * 
	 * @param hqWin
	 *            输赢金额 无负数 0为输掉投注金额
	 */
	public void setHqWin(Double hqWin) {
		this.hqWin = hqWin;
	}

	/**
	 * Get the 输赢金额 无负数 0为输掉投注金额.
	 * 
	 * @return 输赢金额 无负数 0为输掉投注金额
	 */
	public Double getHqWin() {
		return this.hqWin;
	}

	/**
	 * Set the 有效投注额.
	 * 
	 * @param hqTm
	 *            有效投注额
	 */
	public void setHqTm(Double hqTm) {
		this.hqTm = hqTm;
	}

	/**
	 * Get the 有效投注额.
	 * 
	 * @return 有效投注额
	 */
	public Double getHqTm() {
		return this.hqTm;
	}

	/**
	 * Set the 结果.
	 * 
	 * @param hqWer
	 *            结果
	 */
	public void setHqWer(String hqWer) {
		this.hqWer = hqWer;
	}

	/**
	 * Get the 结果.
	 * 
	 * @return 结果
	 */
	public String getHqWer() {
		return this.hqWer;
	}

	/**
	 * Set the 投注编号.
	 * 
	 * @param hqRec
	 *            投注编号
	 */
	public void setHqRec(String hqRec) {
		this.hqRec = hqRec;
	}

	/**
	 * Get the 投注编号.
	 * 
	 * @return 投注编号
	 */
	public String getHqRec() {
		return this.hqRec;
	}

	/**
	 * Set the 牌面.
	 * 
	 * @param hqCrd
	 *            牌面
	 */
	public void setHqCrd(String hqCrd) {
		this.hqCrd = hqCrd;
	}

	/**
	 * Get the 牌面.
	 * 
	 * @return 牌面
	 */
	public String getHqCrd() {
		return this.hqCrd;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param hqCreatetime
	 *            平台更新时间
	 */
	public void setHqCreatetime(Date hqCreatetime) {
		this.hqCreatetime = hqCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getHqCreatetime() {
		return this.hqCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hqId == null) ? 0 : hqId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqHq other = (BettingHqHq) obj;
		if (hqId == null) {
			if (other.hqId != null) {
				return false;
			}
		} else if (!hqId.equals(other.hqId)) {
			return false;
		}
		return true;
	}

}
