package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_sa.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingSa implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 投注ID. */
	private String betid;

	/** 企业编码. */
	private String enterprisecode;

	/** 企业品牌编码. */
	private String brandcode;

	/** 员工编码. */
	private String employeecode;

	/** 员工上级编码. */
	private String parentemployeecode;
	
	/** 会员账号 */
	private String loginaccount;

	/** 查询开始时间. */
	private Date bettime;

	/** 结算时间. */
	private Date payouttime;

	/** 用户名. */
	private String username;

	/** 桌台 ID. */
	private String hostid;

	/** 游戏 ID. */
	private String gameid;

	/** 局. */
	private String round;

	/** 靴. */
	private String sets;

	/** 下注额. */
	private Double betamount;

	/** 结算. */
	private Double resultamount;

	/** 游戏类型. */
	private String gametype;

	/** 投注类型. */
	private String bettype;

	/** 投注来源. */
	private String betsource;

	/** 下注是否成功. */
	private String state;

	/** 其他详情. */
	private String detail;

	/** 数据生成时间. */
	private Date createtime;
	
	/**
	 * 有效投注额
	 */
	private Double validbet;

	/**
	 * Constructor.
	 */
	public BettingSa() {
	}

	/**
	 * Set the 投注ID.
	 * 
	 * @param betid
	 *            投注ID
	 */
	public void setBetid(String betid) {
		this.betid = betid;
	}

	/**
	 * Get the 投注ID.
	 * 
	 * @return 投注ID
	 */
	public String getBetid() {
		return this.betid;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 企业品牌编码.
	 * 
	 * @param brandcode
	 *            企业品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 企业品牌编码.
	 * 
	 * @return 企业品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 员工上级编码.
	 * 
	 * @param parentemployeecode
	 *            员工上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 员工上级编码.
	 * 
	 * @return 员工上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	public String getLoginaccount() {
		return loginaccount;
	}

	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Set the 查询开始时间.
	 * 
	 * @param bettime
	 *            查询开始时间
	 */
	public void setBettime(Date bettime) {
		this.bettime = bettime;
	}

	/**
	 * Get the 查询开始时间.
	 * 
	 * @return 查询开始时间
	 */
	public Date getBettime() {
		return this.bettime;
	}

	/**
	 * Set the 结算时间.
	 * 
	 * @param payouttime
	 *            结算时间
	 */
	public void setPayouttime(Date payouttime) {
		this.payouttime = payouttime;
	}

	/**
	 * Get the 结算时间.
	 * 
	 * @return 结算时间
	 */
	public Date getPayouttime() {
		return this.payouttime;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param username
	 *            用户名
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the 桌台 ID.
	 * 
	 * @param hostid
	 *            桌台 ID
	 */
	public void setHostid(String hostid) {
		this.hostid = hostid;
	}

	/**
	 * Get the 桌台 ID.
	 * 
	 * @return 桌台 ID
	 */
	public String getHostid() {
		return this.hostid;
	}

	/**
	 * Set the 游戏 ID.
	 * 
	 * @param gameid
	 *            游戏 ID
	 */
	public void setGameid(String gameid) {
		this.gameid = gameid;
	}

	/**
	 * Get the 游戏 ID.
	 * 
	 * @return 游戏 ID
	 */
	public String getGameid() {
		return this.gameid;
	}

	/**
	 * Set the 局.
	 * 
	 * @param round
	 *            局
	 */
	public void setRound(String round) {
		this.round = round;
	}

	/**
	 * Get the 局.
	 * 
	 * @return 局
	 */
	public String getRound() {
		return this.round;
	}

	/**
	 * Set the 靴.
	 * 
	 * @param sets
	 *            靴
	 */
	public void setSets(String sets) {
		this.sets = sets;
	}

	/**
	 * Get the 靴.
	 * 
	 * @return 靴
	 */
	public String getSets() {
		return this.sets;
	}

	/**
	 * Set the 下注额.
	 * 
	 * @param betamount
	 *            下注额
	 */
	public void setBetamount(Double betamount) {
		this.betamount = betamount;
	}

	/**
	 * Get the 下注额.
	 * 
	 * @return 下注额
	 */
	public Double getBetamount() {
		return this.betamount;
	}

	/**
	 * Set the 结算.
	 * 
	 * @param resultamount
	 *            结算
	 */
	public void setResultamount(Double resultamount) {
		this.resultamount = resultamount;
	}

	/**
	 * Get the 结算.
	 * 
	 * @return 结算
	 */
	public Double getResultamount() {
		return this.resultamount;
	}

	/**
	 * Set the 游戏类型.
	 * 
	 * @param gametype
	 *            游戏类型
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏类型.
	 * 
	 * @return 游戏类型
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 投注类型.
	 * 
	 * @param bettype
	 *            投注类型
	 */
	public void setBettype(String bettype) {
		this.bettype = bettype;
	}

	/**
	 * Get the 投注类型.
	 * 
	 * @return 投注类型
	 */
	public String getBettype() {
		return this.bettype;
	}

	/**
	 * Set the 投注来源.
	 * 
	 * @param betsource
	 *            投注来源
	 */
	public void setBetsource(String betsource) {
		this.betsource = betsource;
	}

	/**
	 * Get the 投注来源.
	 * 
	 * @return 投注来源
	 */
	public String getBetsource() {
		return this.betsource;
	}

	/**
	 * Set the 下注是否成功.
	 * 
	 * @param state
	 *            下注是否成功
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * Get the 下注是否成功.
	 * 
	 * @return 下注是否成功
	 */
	public String getState() {
		return this.state;
	}

	/**
	 * Set the 其他详情.
	 * 
	 * @param detail
	 *            其他详情
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the 其他详情.
	 * 
	 * @return 其他详情
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the 数据生成时间.
	 * 
	 * @param createtime
	 *            数据生成时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 数据生成时间.
	 * 
	 * @return 数据生成时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((betid == null) ? 0 : betid.hashCode());
		result = prime * result + ((parentemployeecode == null) ? 0 : parentemployeecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingSa other = (BettingSa) obj;
		if (betid == null) {
			if (other.betid != null) {
				return false;
			}
		} else if (!betid.equals(other.betid)) {
			return false;
		}
		if (parentemployeecode == null) {
			if (other.parentemployeecode != null) {
				return false;
			}
		} else if (!parentemployeecode.equals(other.parentemployeecode)) {
			return false;
		}
		return true;
	}

	public Double getValidbet() {
		return validbet;
	}

	public void setValidbet(Double validbet) {
		this.validbet = validbet;
	}

}
