package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of betting_hq_og_ibc.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BettingHqOgIbc implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 唯一ID. */
	private String ibcRowguid;
	
	/** 企业编码 */
	private String enterprisecode;

	/** brandcode. */
	private String brandcode;
	
	/** 用户编码 */
	private String employeecode;
	
	/*** 上级编码 */
    private String parentemployeecode;
	
	/** 用户登录账号 */
	private String loginaccount;

	/** 场次ID. */
	private String ibcBallid;

	/** 开赛时间. */
	private Date ibcBalltime;

	/** 下注内容. */
	private String ibcContent;

	/** 赔率. */
	private String ibcCurpl;

	/** 单双. */
	private String ibcDs;

	/** 大小个数. */
	private String ibcDxc;

	/** 游戏类别. */
	private String ibcIsbk;

	/** 是否取消. */
	private String ibcIscancel;

	/** 是否危险球. */
	private String ibcIsdanger;

	/** 是否结算. */
	private String ibcIsjs;

	/** 输掉的金额. */
	private Double ibcLose;

	/** 联赛ID. */
	private String ibcMatchid;

	/** 货币比率. */
	private String ibcMoneyrate;

	/** 投注单号. */
	private String ibcOrderid;

	/** 红牌. */
	private String ibcRecard;

	/** 赛事结果. */
	private String ibcResult;

	/** 让球个数. */
	private String ibcRqc;

	/** 让球队伍. */
	private String ibcRqteam;

	/** 下注球类ID号. */
	private String ibcSportid;

	/** 走地时间. */
	private String ibcTballtime;

	/** 结算日期. */
	private String ibcThisdate;

	/** 赢半，赢，输半，输，和. */
	private String ibcTruewin;

	/** 投注IP，ibc 不提供，为空就行. */
	private String ibcTzip;

	/** 下注金额. */
	private Double ibcTzmoney;

	/** 下注队伍. */
	private String ibcTzteam;

	/** 下注类别. */
	private String ibcTztype;

	/** 下注时间. */
	private Date ibcUpdatetime;

	/** 会员名. */
	private String ibcUsername;

	/** 赢的钱. */
	private Double ibcWin;

	/** 走地比分. */
	private String ibcZdbf;

	/** 注单更新顺序号. */
	private String ibcVendorid;

	/** 平台更新时间. */
	private Date ibcCreatetime;

	/** Last_Time. */
	private Date lastTime;
	
	/* 查询条件:开始条数*/
	private Integer start;
	/* 查询条件:查询条数 */
	private Integer limit;

	/**
	 * Constructor.
	 */
	public BettingHqOgIbc() {
	}

	/**
	 * Set the 唯一ID.
	 * 
	 * @param ibcRowguid
	 *            唯一ID
	 */
	public void setIbcRowguid(String ibcRowguid) {
		this.ibcRowguid = ibcRowguid;
	}

	/**
	 * Get the 唯一ID.
	 * 
	 * @return 唯一ID
	 */
	public String getIbcRowguid() {
		return this.ibcRowguid;
	}
	
	/**
	 * Get the 企业编码
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}


	/**
	 * Set the brandcode.
	 * 
	 * @param brandcode
	 *            brandcode
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the brandcode.
	 * 
	 * @return brandcode
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Get the 员工编码.
	 * @return
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	/**
	 * Set the 员工编码.
	 * @param employeecode
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}
	
	/**
	 * Get the parentemployeecode.
	 * 
	 * @return parentemployeecode
	 */
	public String getParentemployeecode() {
		return parentemployeecode;
	}

	/**
	 * Set the parentemployeecode.
	 * 
	 * @param parentemployeecode
	 *            parentemployeecode
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 登陆账号.
	 * @return
	 */
	public String getLoginaccount() {
		return loginaccount;
	}

	/**
	 * Set the 登陆账号.
	 * @param employeecode
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}
	
	/**
	 * Set the 场次ID.
	 * 
	 * @param ibcBallid
	 *            场次ID
	 */
	public void setIbcBallid(String ibcBallid) {
		this.ibcBallid = ibcBallid;
	}

	/**
	 * Get the 场次ID.
	 * 
	 * @return 场次ID
	 */
	public String getIbcBallid() {
		return this.ibcBallid;
	}

	/**
	 * Set the 开赛时间.
	 * 
	 * @param ibcBalltime
	 *            开赛时间
	 */
	public void setIbcBalltime(Date ibcBalltime) {
		this.ibcBalltime = ibcBalltime;
	}

	/**
	 * Get the 开赛时间.
	 * 
	 * @return 开赛时间
	 */
	public Date getIbcBalltime() {
		return this.ibcBalltime;
	}

	/**
	 * Set the 下注内容.
	 * 
	 * @param ibcContent
	 *            下注内容
	 */
	public void setIbcContent(String ibcContent) {
		this.ibcContent = ibcContent;
	}

	/**
	 * Get the 下注内容.
	 * 
	 * @return 下注内容
	 */
	public String getIbcContent() {
		return this.ibcContent;
	}

	/**
	 * Set the 赔率.
	 * 
	 * @param ibcCurpl
	 *            赔率
	 */
	public void setIbcCurpl(String ibcCurpl) {
		this.ibcCurpl = ibcCurpl;
	}

	/**
	 * Get the 赔率.
	 * 
	 * @return 赔率
	 */
	public String getIbcCurpl() {
		return this.ibcCurpl;
	}

	/**
	 * Set the 单双.
	 * 
	 * @param ibcDs
	 *            单双
	 */
	public void setIbcDs(String ibcDs) {
		this.ibcDs = ibcDs;
	}

	/**
	 * Get the 单双.
	 * 
	 * @return 单双
	 */
	public String getIbcDs() {
		return this.ibcDs;
	}

	/**
	 * Set the 大小个数.
	 * 
	 * @param ibcDxc
	 *            大小个数
	 */
	public void setIbcDxc(String ibcDxc) {
		this.ibcDxc = ibcDxc;
	}

	/**
	 * Get the 大小个数.
	 * 
	 * @return 大小个数
	 */
	public String getIbcDxc() {
		return this.ibcDxc;
	}

	/**
	 * Set the 游戏类别.
	 * 
	 * @param ibcIsbk
	 *            游戏类别
	 */
	public void setIbcIsbk(String ibcIsbk) {
		this.ibcIsbk = ibcIsbk;
	}

	/**
	 * Get the 游戏类别.
	 * 
	 * @return 游戏类别
	 */
	public String getIbcIsbk() {
		return this.ibcIsbk;
	}

	/**
	 * Set the 是否取消.
	 * 
	 * @param ibcIscancel
	 *            是否取消
	 */
	public void setIbcIscancel(String ibcIscancel) {
		this.ibcIscancel = ibcIscancel;
	}

	/**
	 * Get the 是否取消.
	 * 
	 * @return 是否取消
	 */
	public String getIbcIscancel() {
		return this.ibcIscancel;
	}

	/**
	 * Set the 是否危险球.
	 * 
	 * @param ibcIsdanger
	 *            是否危险球
	 */
	public void setIbcIsdanger(String ibcIsdanger) {
		this.ibcIsdanger = ibcIsdanger;
	}

	/**
	 * Get the 是否危险球.
	 * 
	 * @return 是否危险球
	 */
	public String getIbcIsdanger() {
		return this.ibcIsdanger;
	}

	/**
	 * Set the 是否结算.
	 * 
	 * @param ibcIsjs
	 *            是否结算
	 */
	public void setIbcIsjs(String ibcIsjs) {
		this.ibcIsjs = ibcIsjs;
	}

	/**
	 * Get the 是否结算.
	 * 
	 * @return 是否结算
	 */
	public String getIbcIsjs() {
		return this.ibcIsjs;
	}

	/**
	 * Set the 输掉的金额.
	 * 
	 * @param ibcLose
	 *            输掉的金额
	 */
	public void setIbcLose(Double ibcLose) {
		this.ibcLose = ibcLose;
	}

	/**
	 * Get the 输掉的金额.
	 * 
	 * @return 输掉的金额
	 */
	public Double getIbcLose() {
		return this.ibcLose;
	}

	/**
	 * Set the 联赛ID.
	 * 
	 * @param ibcMatchid
	 *            联赛ID
	 */
	public void setIbcMatchid(String ibcMatchid) {
		this.ibcMatchid = ibcMatchid;
	}

	/**
	 * Get the 联赛ID.
	 * 
	 * @return 联赛ID
	 */
	public String getIbcMatchid() {
		return this.ibcMatchid;
	}

	/**
	 * Set the 货币比率.
	 * 
	 * @param ibcMoneyrate
	 *            货币比率
	 */
	public void setIbcMoneyrate(String ibcMoneyrate) {
		this.ibcMoneyrate = ibcMoneyrate;
	}

	/**
	 * Get the 货币比率.
	 * 
	 * @return 货币比率
	 */
	public String getIbcMoneyrate() {
		return this.ibcMoneyrate;
	}

	/**
	 * Set the 投注单号.
	 * 
	 * @param ibcOrderid
	 *            投注单号
	 */
	public void setIbcOrderid(String ibcOrderid) {
		this.ibcOrderid = ibcOrderid;
	}

	/**
	 * Get the 投注单号.
	 * 
	 * @return 投注单号
	 */
	public String getIbcOrderid() {
		return this.ibcOrderid;
	}

	/**
	 * Set the 红牌.
	 * 
	 * @param ibcRecard
	 *            红牌
	 */
	public void setIbcRecard(String ibcRecard) {
		this.ibcRecard = ibcRecard;
	}

	/**
	 * Get the 红牌.
	 * 
	 * @return 红牌
	 */
	public String getIbcRecard() {
		return this.ibcRecard;
	}

	/**
	 * Set the 赛事结果.
	 * 
	 * @param ibcResult
	 *            赛事结果
	 */
	public void setIbcResult(String ibcResult) {
		this.ibcResult = ibcResult;
	}

	/**
	 * Get the 赛事结果.
	 * 
	 * @return 赛事结果
	 */
	public String getIbcResult() {
		return this.ibcResult;
	}

	/**
	 * Set the 让球个数.
	 * 
	 * @param ibcRqc
	 *            让球个数
	 */
	public void setIbcRqc(String ibcRqc) {
		this.ibcRqc = ibcRqc;
	}

	/**
	 * Get the 让球个数.
	 * 
	 * @return 让球个数
	 */
	public String getIbcRqc() {
		return this.ibcRqc;
	}

	/**
	 * Set the 让球队伍.
	 * 
	 * @param ibcRqteam
	 *            让球队伍
	 */
	public void setIbcRqteam(String ibcRqteam) {
		this.ibcRqteam = ibcRqteam;
	}

	/**
	 * Get the 让球队伍.
	 * 
	 * @return 让球队伍
	 */
	public String getIbcRqteam() {
		return this.ibcRqteam;
	}

	/**
	 * Set the 下注球类ID号.
	 * 
	 * @param ibcSportid
	 *            下注球类ID号
	 */
	public void setIbcSportid(String ibcSportid) {
		this.ibcSportid = ibcSportid;
	}

	/**
	 * Get the 下注球类ID号.
	 * 
	 * @return 下注球类ID号
	 */
	public String getIbcSportid() {
		return this.ibcSportid;
	}

	/**
	 * Set the 走地时间.
	 * 
	 * @param ibcTballtime
	 *            走地时间
	 */
	public void setIbcTballtime(String ibcTballtime) {
		this.ibcTballtime = ibcTballtime;
	}

	/**
	 * Get the 走地时间.
	 * 
	 * @return 走地时间
	 */
	public String getIbcTballtime() {
		return this.ibcTballtime;
	}

	/**
	 * Set the 结算日期.
	 * 
	 * @param ibcThisdate
	 *            结算日期
	 */
	public void setIbcThisdate(String ibcThisdate) {
		this.ibcThisdate = ibcThisdate;
	}

	/**
	 * Get the 结算日期.
	 * 
	 * @return 结算日期
	 */
	public String getIbcThisdate() {
		return this.ibcThisdate;
	}

	/**
	 * Set the 赢半，赢，输半，输，和.
	 * 
	 * @param ibcTruewin
	 *            赢半，赢，输半，输，和
	 */
	public void setIbcTruewin(String ibcTruewin) {
		this.ibcTruewin = ibcTruewin;
	}

	/**
	 * Get the 赢半，赢，输半，输，和.
	 * 
	 * @return 赢半，赢，输半，输，和
	 */
	public String getIbcTruewin() {
		return this.ibcTruewin;
	}

	/**
	 * Set the 投注IP，ibc 不提供，为空就行.
	 * 
	 * @param ibcTzip
	 *            投注IP，ibc 不提供，为空就行
	 */
	public void setIbcTzip(String ibcTzip) {
		this.ibcTzip = ibcTzip;
	}

	/**
	 * Get the 投注IP，ibc 不提供，为空就行.
	 * 
	 * @return 投注IP，ibc 不提供，为空就行
	 */
	public String getIbcTzip() {
		return this.ibcTzip;
	}

	/**
	 * Set the 下注金额.
	 * 
	 * @param ibcTzmoney
	 *            下注金额
	 */
	public void setIbcTzmoney(Double ibcTzmoney) {
		this.ibcTzmoney = ibcTzmoney;
	}

	/**
	 * Get the 下注金额.
	 * 
	 * @return 下注金额
	 */
	public Double getIbcTzmoney() {
		return this.ibcTzmoney;
	}

	/**
	 * Set the 下注队伍.
	 * 
	 * @param ibcTzteam
	 *            下注队伍
	 */
	public void setIbcTzteam(String ibcTzteam) {
		this.ibcTzteam = ibcTzteam;
	}

	/**
	 * Get the 下注队伍.
	 * 
	 * @return 下注队伍
	 */
	public String getIbcTzteam() {
		return this.ibcTzteam;
	}

	/**
	 * Set the 下注类别.
	 * 
	 * @param ibcTztype
	 *            下注类别
	 */
	public void setIbcTztype(String ibcTztype) {
		this.ibcTztype = ibcTztype;
	}

	/**
	 * Get the 下注类别.
	 * 
	 * @return 下注类别
	 */
	public String getIbcTztype() {
		return this.ibcTztype;
	}

	/**
	 * Set the 下注时间.
	 * 
	 * @param ibcUpdatetime
	 *            下注时间
	 */
	public void setIbcUpdatetime(Date ibcUpdatetime) {
		this.ibcUpdatetime = ibcUpdatetime;
	}

	/**
	 * Get the 下注时间.
	 * 
	 * @return 下注时间
	 */
	public Date getIbcUpdatetime() {
		return this.ibcUpdatetime;
	}

	/**
	 * Set the 会员名.
	 * 
	 * @param ibcUsername
	 *            会员名
	 */
	public void setIbcUsername(String ibcUsername) {
		this.ibcUsername = ibcUsername;
	}

	/**
	 * Get the 会员名.
	 * 
	 * @return 会员名
	 */
	public String getIbcUsername() {
		return this.ibcUsername;
	}

	/**
	 * Set the 赢的钱.
	 * 
	 * @param ibcWin
	 *            赢的钱
	 */
	public void setIbcWin(Double ibcWin) {
		this.ibcWin = ibcWin;
	}

	/**
	 * Get the 赢的钱.
	 * 
	 * @return 赢的钱
	 */
	public Double getIbcWin() {
		return this.ibcWin;
	}

	/**
	 * Set the 走地比分.
	 * 
	 * @param ibcZdbf
	 *            走地比分
	 */
	public void setIbcZdbf(String ibcZdbf) {
		this.ibcZdbf = ibcZdbf;
	}

	/**
	 * Get the 走地比分.
	 * 
	 * @return 走地比分
	 */
	public String getIbcZdbf() {
		return this.ibcZdbf;
	}

	/**
	 * Set the 注单更新顺序号.
	 * 
	 * @param ibcVendorid
	 *            注单更新顺序号
	 */
	public void setIbcVendorid(String ibcVendorid) {
		this.ibcVendorid = ibcVendorid;
	}

	/**
	 * Get the 注单更新顺序号.
	 * 
	 * @return 注单更新顺序号
	 */
	public String getIbcVendorid() {
		return this.ibcVendorid;
	}

	/**
	 * Set the 平台更新时间.
	 * 
	 * @param ibcCreatetime
	 *            平台更新时间
	 */
	public void setIbcCreatetime(Date ibcCreatetime) {
		this.ibcCreatetime = ibcCreatetime;
	}

	/**
	 * Get the 平台更新时间.
	 * 
	 * @return 平台更新时间
	 */
	public Date getIbcCreatetime() {
		return this.ibcCreatetime;
	}

	/**
	 * Set the Last_Time.
	 * 
	 * @param lastTime
	 *            Last_Time
	 */
	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * Get the Last_Time.
	 * 
	 * @return Last_Time
	 */
	public Date getLastTime() {
		return this.lastTime;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ibcRowguid == null) ? 0 : ibcRowguid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BettingHqOgIbc other = (BettingHqOgIbc) obj;
		if (ibcRowguid == null) {
			if (other.ibcRowguid != null) {
				return false;
			}
		} else if (!ibcRowguid.equals(other.ibcRowguid)) {
			return false;
		}
		return true;
	}

}
