package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Model class of employee_registerlink.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BrandDomain implements Serializable,Cloneable{

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** 主键 */
	private Integer domaincode;

	/** 注册域名. */
	private String domainlink;
	
	/** 企业编码 */
	private String enterprisecode;
	
	/** 品牌编码 */
	private String brandcode;

	/** 用户编码 */
	private String employeecode;
	
	/** 上级编码. */
	private String parentemployeecode;

	/** 用户类型. */
	private String employeetype;

	/** 分红. */
	private BigDecimal dividend;

	/** 占成. */
	private BigDecimal share;

	/** 洗码. */
	private String bonus;
	
	/** 域名类型 */
	private Byte domaintype;
	
	/** 是否默认 */
	private Byte isdefualt;
	
	/** 域名所属权 */
	private Byte copyright;
	
	/** 二级域名指向的主域名 */
	private Integer linkdomain;
	
	/** 创建时间 */
	private Date createdate;
	

	/** 链接状态(1、启用 2、禁用). */
	private String linkstatus;

	/** 站点模板 */
	private String webtemplatecode;
	
	/** 数据状态. */
	private String datastatus;
	
	/* 关联字段：站点模板名称 */
	private String templatename;
	/* 视图字段:品牌名称 */
	private String brandname;
	
	/*  视图字段：品牌logo */
	private String brandlogo;
	
	/* 加密字段 */
	private String sign;
	
	/* 视图字段:企业名称 */
	private String enterpriseName;
	
	/* 视图字段:所属人名称 */
	private String employeeName;
	
	/* 视图字段:上级人名称 */
	private String parentemployeeName;
	
	/* 业务字段:上级人名称 */
	private Byte[] domaintypes;
	/* 业务字段：区分该域名拥有者是现金代理还是信用代理 */
	private String agenttype;
	

	/**
	 * Constructor.
	 */
	public BrandDomain() {
	}

	public BrandDomain(Integer domaincode,String bonus) {
		this.domaincode = domaincode;
		this.bonus = bonus;
	}
	
	public BrandDomain(String employeecode,Enum_linkstatus linkstatus,Byte[] domaintype) {
		this.employeecode = employeecode;
		this.linkstatus = linkstatus.value;
		this.domaintypes = domaintype;
	}
	
	public enum Enum_linkstatus{
		启用("1","启用"),
		禁用("2","禁用");
	  public String value;
      public String desc;
      private Enum_linkstatus(String _value, String _desc) {
          this.value = _value;
          this.desc = _desc;
      }
      public String getDesc() {  
          return desc;  
      } 
      public String getValue() {  
          return value;  
      }  
	}
	
	public enum Enum_copyright{
		公共("1","公共"),
		私有("2","私有");
	  public String value;
      public String desc;
      private Enum_copyright(String _value, String _desc) {
          this.value = _value;
          this.desc = _desc;
      }
      public String getDesc() {  
          return desc;  
      } 
      public String getValue() {  
          return value;  
      }  
	}
	
	public enum Enum_domaintype{
		企业域名_会员站点(1,"企业域名_会员站点"),
		会员站点(2,"会员站点"),
		代理注册链接(3,"代理注册链接"),
		代理站点(4,"代理站点"),
		企业域名_代理站点(5,"企业域名_代理站点")
		;
		  public Integer value;
	      public String desc;
	      private Enum_domaintype(Integer _value, String _desc) {
	          this.value = _value;
	          this.desc = _desc;
	      }
	      public String getDesc() {  
	          return desc;  
	      } 
	      public Integer getValue() {  
	          return value;  
	      }  
		}
	/**
	 * Set the 注册编码.
	 * 
	 * @param registercode
	 *            注册编码
	 */
	public void setDomainlink(String domainlink) {
		this.domainlink = domainlink;
	}

	/**
	 * Get the 注册编码.
	 * 
	 * @return 注册编码
	 */
	public String getDomainlink() {
		return this.domainlink;
	}

	public String getEnterprisecode() {
		return enterprisecode;
	}

	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	public String getBrandcode() {
		return brandcode;
	}

	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}


	/**
	 * Set the 用户类型.
	 * 
	 * @param employeetype
	 *            用户类型
	 */
	public void setEmployeetype(String employeetype) {
		this.employeetype = employeetype;
	}

	/**
	 * Get the 用户类型.
	 * 
	 * @return 用户类型
	 */
	public String getEmployeetype() {
		return this.employeetype;
	}

	/**
	 * Set the 分红.
	 * 
	 * @param dividend
	 *            分红
	 */
	public void setDividend(BigDecimal dividend) {
		this.dividend = dividend;
	}

	/**
	 * Get the 分红.
	 * 
	 * @return 分红
	 */
	public BigDecimal getDividend() {
		return this.dividend;
	}

	/**
	 * Set the 占成.
	 * 
	 * @param share
	 *            占成
	 */
	public void setShare(BigDecimal share) {
		this.share = share;
	}

	/**
	 * Get the 占成.
	 * 
	 * @return 占成
	 */
	public BigDecimal getShare() {
		return this.share;
	}


	public Byte getIsdefualt() {
		return isdefualt;
	}

	public void setIsdefualt(Byte isdefualt) {
		this.isdefualt = isdefualt;
	}

	/**
	 * Set the 洗码.
	 * 
	 * @param bonus
	 *            洗码
	 */
	public void setBonus(String bonus) {
		this.bonus = bonus;
	}

	/**
	 * Get the 洗码.
	 * 
	 * @return 洗码
	 */
	public String getBonus() {
		return this.bonus;
	}

	/**
	 * Set the 链接状态(1、启用 2、禁用).
	 * 
	 * @param linkstatus
	 *            链接状态(1、启用 2、禁用)
	 */
	public void setLinkstatus(String linkstatus) {
		this.linkstatus = linkstatus;
	}

	/**
	 * Get the 链接状态(1、启用 2、禁用).
	 * 
	 * @return 链接状态(1、启用 2、禁用)
	 */
	public String getLinkstatus() {
		return this.linkstatus;
	}

	/**
	 * Set the 数据状态.
	 * 
	 * @param datastatus
	 *            数据状态
	 */
	public void setDatastatus(String datastatus) {
		this.datastatus = datastatus;
	}

	/**
	 * Get the 数据状态.
	 * 
	 * @return 数据状态
	 */
	public String getDatastatus() {
		return this.datastatus;
	}

	public String getBrandlogo() {
		return brandlogo;
	}

	public String getBrandname() {
		return brandname;
	}

	public String getTemplatename() {
		return templatename;
	}

	public void setTemplatename(String templatename) {
		this.templatename = templatename;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public Byte getDomaintype() {
		return domaintype;
	}

	public void setDomaintype(Byte domaintype) {
		this.domaintype = domaintype;
	}

	public void setBrandlogo(String brandlogo) {
		this.brandlogo = brandlogo;
	}

	public String getEmployeecode() {
		return employeecode;
	}

	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	public String getParentemployeecode() {
		return parentemployeecode;
	}

	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	public Integer getDomaincode() {
		return domaincode;
	}

	public void setDomaincode(Integer domaincode) {
		this.domaincode = domaincode;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Byte getCopyright() {
		return copyright;
	}

	public void setCopyright(Byte copyright) {
		this.copyright = copyright;
	}

	public String getWebtemplatecode() {
		return webtemplatecode;
	}

	public void setWebtemplatecode(String webtemplatecode) {
		this.webtemplatecode = webtemplatecode;
	}

	public Integer getLinkdomain() {
		return linkdomain;
	}

	public void setLinkdomain(Integer linkdomain) {
		this.linkdomain = linkdomain;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getEnterpriseName() {
		return enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getParentemployeeName() {
		return parentemployeeName;
	}

	public void setParentemployeeName(String parentemployeeName) {
		this.parentemployeeName = parentemployeeName;
	}

	public Byte[] getDomaintypes() {
		return domaintypes;
	}


	public void setDomaintypes(Byte[] domaintypes) {
		this.domaintypes = domaintypes;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((domainlink == null) ? 0 : domainlink.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BrandDomain other = (BrandDomain) obj;
		if (domainlink == null) {
			if (other.domainlink != null) {
				return false;
			}
		} else if (!domainlink.equals(other.domainlink)) {
			return false;
		}
		return true;
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public String getAgenttype() {
		return agenttype;
	}

	public void setAgenttype(String agenttype) {
		this.agenttype = agenttype;
	}

}
