package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of deposit_withdral_order_delegate.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DepositWithdralOrderDelegate implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 委派编码. */
	private Integer delegatecode;

	/** 流程编码 */
	private String flowcode;
	
	/** 流程名字 */
	private String flowname;

	/** 订单编码. */
	private String ordernumber;

	/** 委派人编码. */
	private String assignedtocode;

	/** 委派人名称. */
	private String assignedtoaccount;

	/** 开始处理时间. */
	private Date begintime;
	
	/** 结束处理时间 */
	private Date endtime;

	/** 处理时长. */
	private Integer processduration;

	/** 超时处理原因. */
	private String overtimereason;

	/** 图片路径. */
	private String imgname;

	/** 审核结果. */
	private Byte auditresult;

	/** 审核说明. */
	private String auditdesc;
	
	
	
	public enum Enum_auditresult{
		通过(1,"通过"),
		驳回(2,"驳回"),
		拒绝(3,"拒绝");
		public Integer value;
		public String desc;
        private Enum_auditresult(Integer value,String desc) {
            this.value = value;
            this.desc = desc;
        }
	}
	/**
	 * Constructor.
	 */
	public DepositWithdralOrderDelegate() {
	}
	
	/**
	 * Constructor.
	 */
	public DepositWithdralOrderDelegate(String  ordernumber, String flowcode,Integer processduration) {
		this.ordernumber = ordernumber;
		this.flowcode = flowcode;
		this.processduration = processduration;
		this.begintime = new Date();
	}

	public String getFlowname() {
		return flowname;
	}

	public void setFlowname(String flowname) {
		this.flowname = flowname;
	}
	
	
	public String getFlowcode() {
		return flowcode;
	}

	public void setFlowcode(String flowcode) {
		this.flowcode = flowcode;
	}

	
	
	/**
	 * Set the 委派编码.
	 * 
	 * @param delegatecode
	 *            委派编码
	 */
	public void setDelegatecode(Integer delegatecode) {
		this.delegatecode = delegatecode;
	}

	/**
	 * Get the 委派编码.
	 * 
	 * @return 委派编码
	 */
	public Integer getDelegatecode() {
		return this.delegatecode;
	}

	/**
	 * Set the 订单编码.
	 * 
	 * @param ordercode
	 *            订单编码
	 */
	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	/**
	 * Get the 订单编码.
	 * 
	 * @return 订单编码
	 */
	public String getOrdernumber() {
		return this.ordernumber;
	}

	/**
	 * Set the 委派人编码.
	 * 
	 * @param assignedtocode
	 *            委派人编码
	 */
	public void setAssignedtocode(String assignedtocode) {
		this.assignedtocode = assignedtocode;
	}

	/**
	 * Get the 委派人编码.
	 * 
	 * @return 委派人编码
	 */
	public String getAssignedtocode() {
		return this.assignedtocode;
	}

	/**
	 * Set the 委派人名称.
	 * 
	 * @param assignedtoaccount
	 *            委派人名称
	 */
	public void setAssignedtoaccount(String assignedtoaccount) {
		this.assignedtoaccount = assignedtoaccount;
	}

	/**
	 * Get the 委派人名称.
	 * 
	 * @return 委派人名称
	 */
	public String getAssignedtoaccount() {
		return this.assignedtoaccount;
	}

	/**
	 * Set the 开始处理时间.
	 * 
	 * @param begintime
	 *            开始处理时间
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * Get the 开始处理时间.
	 * 
	 * @return 开始处理时间
	 */
	public Date getBegintime() {
		return this.begintime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * Set the 处理时长.
	 * 
	 * @param processduration
	 *            处理时长
	 */
	public void setProcessduration(Integer processduration) {
		this.processduration = processduration;
	}

	/**
	 * Get the 处理时长.
	 * 
	 * @return 处理时长
	 */
	public Integer getProcessduration() {
		return this.processduration;
	}

	/**
	 * Set the 超时处理原因.
	 * 
	 * @param overtimereason
	 *            超时处理原因
	 */
	public void setOvertimereason(String overtimereason) {
		this.overtimereason = overtimereason;
	}

	/**
	 * Get the 超时处理原因.
	 * 
	 * @return 超时处理原因
	 */
	public String getOvertimereason() {
		return this.overtimereason;
	}

	/**
	 * Set the 图片路径.
	 * 
	 * @param imgname
	 *            图片路径
	 */
	public void setImgname(String imgname) {
		this.imgname = imgname;
	}

	/**
	 * Get the 图片路径.
	 * 
	 * @return 图片路径
	 */
	public String getImgname() {
		return this.imgname;
	}


	public Byte getAuditresult() {
		return auditresult;
	}

	public void setAuditresult(Byte auditresult) {
		this.auditresult = auditresult;
	}

	/**
	 * Set the 审核说明.
	 * 
	 * @param auditdesc
	 *            审核说明
	 */
	public void setAuditdesc(String auditdesc) {
		this.auditdesc = auditdesc;
	}

	/**
	 * Get the 审核说明.
	 * 
	 * @return 审核说明
	 */
	public String getAuditdesc() {
		return this.auditdesc;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((delegatecode == null) ? 0 : delegatecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DepositWithdralOrderDelegate other = (DepositWithdralOrderDelegate) obj;
		if (delegatecode == null) {
			if (other.delegatecode != null) {
				return false;
			}
		} else if (!delegatecode.equals(other.delegatecode)) {
			return false;
		}
		return true;
	}

}
