package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of employee_available.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmployeeAvailable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工编码. */
	private String employeecode;

	/** 有效截至时间. */
	private Date availabletime;

	/**
	 * Constructor.
	 */
	public EmployeeAvailable() {
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 有效截至时间.
	 * 
	 * @param availabletime
	 *            有效截至时间
	 */
	public void setAvailabletime(Date availabletime) {
		this.availabletime = availabletime;
	}

	/**
	 * Get the 有效截至时间.
	 * 
	 * @return 有效截至时间
	 */
	public Date getAvailabletime() {
		return this.availabletime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employeecode == null) ? 0 : employeecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmployeeAvailable other = (EmployeeAvailable) obj;
		if (employeecode == null) {
			if (other.employeecode != null) {
				return false;
			}
		} else if (!employeecode.equals(other.employeecode)) {
			return false;
		}
		return true;
	}

}
