package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of enterprise_employee.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmployeeRelation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工编码. */
	private String employeecode;
	
	/** 上级编码. */
	private String parentemployeecode;
	
	
	/**
	 * Constructor.
	 */
	public EmployeeRelation() {
	}
	
	public EmployeeRelation(String employeecode,String parentemployeecode) {
		this.employeecode = employeecode;
		this.parentemployeecode = parentemployeecode;
	}


	public String getEmployeecode() {
		return employeecode;
	}


	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}


	public String getParentemployeecode() {
		return parentemployeecode;
	}


	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}



	

}
