package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Model class of employee_gamecataloy_bonus.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EmployeeGamecataloyBonus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工编码. */
	private String employeecode;
	
	/** 用户上级编码 */
	private String parentemployeecode;

	/** 游戏平台标志(唯一). */
	private String gametype;
	
	/** 游戏平台标志名称. */
	private String gamename;

	/** 游戏种类类型标志(唯一). */
	private String categorytype;
	
	/** 游戏种类类型标志名称. */
	private String categoryname;

	/** 洗码. */
	private BigDecimal bonus;
	
	public String getGamename() {
		return gamename;
	}

	public void setGamename(String gamename) {
		this.gamename = gamename;
	}

	public String getCategoryname() {
		return categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
	 * Constructor.
	 */
	public EmployeeGamecataloyBonus() {
	}
	
	public EmployeeGamecataloyBonus(String employeecode,String parentemployeecode) {
		this.employeecode = employeecode;
		this.parentemployeecode = parentemployeecode;
	}

	public EmployeeGamecataloyBonus(String gametype,String categorytype,BigDecimal bonus){
		this.gametype = gametype;
		this.categorytype = categorytype;
		this.bonus = bonus;
	}
	public EmployeeGamecataloyBonus(String employeecode,String parentemployeecode,String gametype,String categorytype,BigDecimal bonus){
		this.employeecode = employeecode;
		this.parentemployeecode = parentemployeecode;
		this.gametype = gametype;
		this.categorytype = categorytype;
		this.bonus = bonus;
	}
	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	public String getParentemployeecode() {
		return parentemployeecode;
	}

	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Set the 游戏平台标志(唯一).
	 * 
	 * @param gametype
	 *            游戏平台标志(唯一)
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏平台标志(唯一).
	 * 
	 * @return 游戏平台标志(唯一)
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 游戏种类类型标志(唯一).
	 * 
	 * @param categorytype
	 *            游戏种类类型标志(唯一)
	 */
	public void setCategorytype(String categorytype) {
		this.categorytype = categorytype;
	}

	/**
	 * Get the 游戏种类类型标志(唯一).
	 * 
	 * @return 游戏种类类型标志(唯一)
	 */
	public String getCategorytype() {
		return this.categorytype;
	}

	/**
	 * Set the 洗码.
	 * 
	 * @param bonus
	 *            洗码
	 */
	public void setBonus(BigDecimal bonus) {
		this.bonus = bonus;
	}

	/**
	 * Get the 洗码.
	 * 
	 * @return 洗码
	 */
	public BigDecimal getBonus() {
		return this.bonus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employeecode == null) ? 0 : employeecode.hashCode());
		result = prime * result + ((gametype == null) ? 0 : gametype.hashCode());
		result = prime * result + ((categorytype == null) ? 0 : categorytype.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EmployeeGamecataloyBonus other = (EmployeeGamecataloyBonus) obj;
		if (employeecode == null) {
			if (other.employeecode != null) {
				return false;
			}
		} else if (!employeecode.equals(other.employeecode)) {
			return false;
		}
		if (gametype == null) {
			if (other.gametype != null) {
				return false;
			}
		} else if (!gametype.equals(other.gametype)) {
			return false;
		}
		if (categorytype == null) {
			if (other.categorytype != null) {
				return false;
			}
		} else if (!categorytype.equals(other.categorytype)) {
			return false;
		}
		return true;
	}

}
