package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of enterprise_employee_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseEmployeeType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工类别编码. */
	private String employeetypecode;

	/** 员工类别. */
	private String employeetype;
	
	public enum Type{
		企业号("T001","企业号"),
		员工("T002","员工"),
		会员("T003","会员"),
		代理("T004","代理"),
		信用代理("T005","信用代理");
		
		public String value;
		public String desc;
		
		private Type(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}

	/**
	 * Constructor.
	 */
	public EnterpriseEmployeeType() {
	}

	/**
	 * Set the 员工类别编码.
	 * 
	 * @param employeetypecode
	 *            员工类别编码
	 */
	public void setEmployeetypecode(String employeetypecode) {
		this.employeetypecode = employeetypecode;
	}

	/**
	 * Get the 员工类别编码.
	 * 
	 * @return 员工类别编码
	 */
	public String getEmployeetypecode() {
		return this.employeetypecode;
	}

	/**
	 * Set the 员工类别.
	 * 
	 * @param employeetype
	 *            员工类别
	 */
	public void setEmployeetype(String employeetype) {
		this.employeetype = employeetype;
	}

	/**
	 * Get the 员工类别.
	 * 
	 * @return 员工类别
	 */
	public String getEmployeetype() {
		return this.employeetype;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employeetypecode == null) ? 0 : employeetypecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseEmployeeType other = (EnterpriseEmployeeType) obj;
		if (employeetypecode == null) {
			if (other.employeetypecode != null) {
				return false;
			}
		} else if (!employeetypecode.equals(other.employeetypecode)) {
			return false;
		}
		return true;
	}

}
