package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Model class of enterprise_operating_brand.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseOperatingBrand implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 品牌编码. */
	private String brandcode;

	/** 企业编码. */
	private String enterprisecode;
	
	/** 企业名称. */
	private String enterprisename;

	/** 品牌名称. */
	private String brandname;

	/** 品牌成立时间. */
	private Date brandfoundedtime;
	
	/** 品牌logo路径 */
	private String logopath;
	
	/** 品牌默认打码倍数 */
	private BigDecimal defualtchip;
	
	/** 模板编码 */
	private String webtemplatecode;
	
	/* 关联对象：前端模板 */
	private WebviewTemplate webtemplate;
	
	/* 关联属性:默认主域名 */
	private String defualtmaindomain;
	
	/**
	 * Constructor.
	 */
	public EnterpriseOperatingBrand() {
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}
	public String getEnterprisename() {
		return enterprisename;
	}

	public void setEnterprisename(String enterprisename) {
		this.enterprisename = enterprisename;
	}
	/**
	 * Set the 品牌名称.
	 * 
	 * @param brandname
	 *            品牌名称
	 */
	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	/**
	 * Get the 品牌名称.
	 * 
	 * @return 品牌名称
	 */
	public String getBrandname() {
		return this.brandname;
	}

	/**
	 * Set the 品牌成立时间.
	 * 
	 * @param brandfoundedtime
	 *            品牌成立时间
	 */
	public void setBrandfoundedtime(Date brandfoundedtime) {
		this.brandfoundedtime = brandfoundedtime;
	}

	/**
	 * Get the 品牌成立时间.
	 * 
	 * @return 品牌成立时间
	 */
	public Date getBrandfoundedtime() {
		return this.brandfoundedtime;
	}

	public String getLogopath() {
		return logopath;
	}

	public void setLogopath(String logopath) {
		this.logopath = logopath;
	}

	public WebviewTemplate getWebtemplate() {
		return webtemplate;
	}

	public void setWebtemplate(WebviewTemplate webtemplate) {
		this.webtemplate = webtemplate;
	}

	public String getDefualtmaindomain() {
		return defualtmaindomain;
	}

	public void setDefualtmaindomain(String defualtmaindomain) {
		this.defualtmaindomain = defualtmaindomain;
	}

	public String getWebtemplatecode() {
		return webtemplatecode;
	}

	public void setWebtemplatecode(String webtemplatecode) {
		this.webtemplatecode = webtemplatecode;
	}

	public BigDecimal getDefualtchip() {
		return defualtchip;
	}

	public void setDefualtchip(BigDecimal defualtchip) {
		this.defualtchip = defualtchip;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((brandcode == null) ? 0 : brandcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseOperatingBrand other = (EnterpriseOperatingBrand) obj;
		if (brandcode == null) {
			if (other.brandcode != null) {
				return false;
			}
		} else if (!brandcode.equals(other.brandcode)) {
			return false;
		}
		return true;
	}

}
