package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Model class of enterprise_employee_level.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseEmployeeLevel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工级别编码. */
	private String employeeLevelCode;

	/** 员工级别名称. */
	private String employeeLevelName;
	
	/** 企业编码 */
	private String enterpriseCode;

	/** 每日取款次数 */
	private int takeTimeOfDay;
	
	/** 每日取款金额 */
	private BigDecimal takeMoneyOfDay;
	
	/*****等级排序，升序*****/
	private int ord;
	
	/*****升级条件，流水*****/
	private String conditionlevel;
	
	/**
	 * 是否默认
	 */
	private String isdefault;
	
	/** 加密 **/
	
	private String sign;
	
	public enum Enum_isdeault{
    	非默认("0","非默认"),
    	默认("1","默认");
		public String value;
		public String desc;
		
		private Enum_isdeault(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}

	public enum EmployeeLevel{
		普通级("普通级","0001"),
		VIP一级("VIP一级 ","0002"),
		VIP二级("VIP二级 ","0003"),
		VIP三级("VIP三级 ","0004"),
		VIP四级("VIP四级 ","0005"),
		VIP五级("VIP五级 ","0006"),
		VIP六级("VIP六级 ","0007"),
		VIP七级("VIP七级 ","0008"),
		VIP八级("VIP八级 ","0009");
		public String value;
		public String desc;
		private EmployeeLevel(String desc,String value){
			this.value=value;
			this.desc=desc;
		}
	}
	
	/**
	 * Constructor.
	 */
	public EnterpriseEmployeeLevel() {
	}

	public String getEmployeeLevelCode() {
		return employeeLevelCode;
	}

	public void setEmployeeLevelCode(String employeeLevelCode) {
		this.employeeLevelCode = employeeLevelCode;
	}

	public String getEmployeeLevelName() {
		return employeeLevelName;
	}

	public void setEmployeeLevelName(String employeeLevelName) {
		this.employeeLevelName = employeeLevelName;
	}

	public String getEnterpriseCode() {
		return enterpriseCode;
	}

	public void setEnterpriseCode(String enterpriseCode) {
		this.enterpriseCode = enterpriseCode;
	}

	public int getTakeTimeOfDay() {
		return takeTimeOfDay;
	}

	public void setTakeTimeOfDay(int takeTimeOfDay) {
		this.takeTimeOfDay = takeTimeOfDay;
	}

	public BigDecimal getTakeMoneyOfDay() {
		return takeMoneyOfDay;
	}

	public void setTakeMoneyOfDay(BigDecimal takeMoneyOfDay) {
		this.takeMoneyOfDay = takeMoneyOfDay;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((employeeLevelName == null) ? 0 : employeeLevelName.hashCode());
		result = prime * result + ((employeeLevelCode == null) ? 0 : employeeLevelCode.hashCode());
		result = prime * result + ((enterpriseCode == null) ? 0 : enterpriseCode.hashCode());
		result = prime * result + ((takeMoneyOfDay == null) ? 0 : takeMoneyOfDay.hashCode());
		result = prime * result + takeTimeOfDay;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EnterpriseEmployeeLevel other = (EnterpriseEmployeeLevel) obj;
		if (employeeLevelName == null) {
			if (other.employeeLevelName != null)
				return false;
		} else if (!employeeLevelName.equals(other.employeeLevelName))
			return false;
		if (employeeLevelCode == null) {
			if (other.employeeLevelCode != null)
				return false;
		} else if (!employeeLevelCode.equals(other.employeeLevelCode))
			return false;
		if (enterpriseCode == null) {
			if (other.enterpriseCode != null)
				return false;
		} else if (!enterpriseCode.equals(other.enterpriseCode))
			return false;
		if (takeMoneyOfDay == null) {
			if (other.takeMoneyOfDay != null)
				return false;
		} else if (!takeMoneyOfDay.equals(other.takeMoneyOfDay))
			return false;
		if (takeTimeOfDay != other.takeTimeOfDay)
			return false;
		return true;
	}

	public String getIsdefault() {
		return isdefault;
	}

	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault;
	}

	public int getOrd() {
		return ord;
	}

	public void setOrd(int ord) {
		this.ord = ord;
	}

	public String getConditionlevel() {
		return conditionlevel;
	}

	public void setConditionlevel(String conditionlevel) {
		this.conditionlevel = conditionlevel;
	}

	

	
}
