package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of enterprise_employee_information.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseEmployeeInformation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 员工信息代码. */
	private String informationcode;
	
	/** 员工编码*/
	private String employeecode;
	
	/** 员工上级编码 */
	private String parentemployeecode;
	
	/** 企业编码	 */
	private String enterprisecode;

	/** 银行代码. */
	private String bankcode;
	
	/** 银行名称. */
	private String bankname;

	/** 账号. */
	private String paymentaccount;

	/** 户名. */
	private String accountname;

	/** 开户支行. */
	private String openningbank;

	/** 电话. */
	private String phonenumber;

	/** QQ. */
	private String qq;

	/** skype. */
	private String skype;

	/** email. */
	private String email;
	
	/** 状态 */
	private String status;

	/** 员工信息备注. */
	private String infomationcomment;
	
	/**品牌编码*/
	private String brandcode;
	
	/**登录账号*/
	private String loginaccount;
	
	
	//账号余额
	private double balance;
	//存款总额
	private double depositTotal;
	//取款总额
	private double takeTotal;
	//注册时间
	private Date registerDate;
	//最后登录时间
	private Date lastLoginDate;
	//IP地址
	private String ip;
	//分红
	private double dividend;
	//占成
	private double share;
	
	
	public double getDividend() {
		return dividend;
	}

	public void setDividend(double dividend) {
		this.dividend = dividend;
	}

	public double getShare() {
		return share;
	}

	public void setShare(double share) {
		this.share = share;
	}


	public enum Enum_status{
		锁定("1","锁定"),
		解锁("2","解锁")
		;
		public String value;
		public String desc;
        private Enum_status(String value,String desc) {
        	this.value = value;
            this.desc = desc;
        }
	}
	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public double getDepositTotal() {
		return depositTotal;
	}

	public void setDepositTotal(double depositTotal) {
		this.depositTotal = depositTotal;
	}

	public double getTakeTotal() {
		return takeTotal;
	}

	public void setTakeTotal(double takeTotal) {
		this.takeTotal = takeTotal;
	}

	public Date getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getLoginaccount() {
		return loginaccount;
	}

	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}
	public String getEnterprisecode() {
		return enterprisecode;
	}

	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	public String getBrandcode() {
		return brandcode;
	}

	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}
	
	public String getBankname() {
		return bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	
	/**
	 * Constructor.
	 */
	public EnterpriseEmployeeInformation() {
	}

	/**
	 * Set the 员工信息代码.
	 * 
	 * @param informationcode
	 *            员工信息代码
	 */
	public void setInformationcode(String informationcode) {
		this.informationcode = informationcode;
	}
	
	/**
	 * Get the 员工code.
	 * 
	 * @return 员工信息代码
	 */
	public String getEmployeecode() {
		return employeecode;
	}

	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}
	
	public String getParentemployeecode() {
		return parentemployeecode;
	}

	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 员工信息代码.
	 * 
	 * @return 员工信息代码
	 */
	public String getInformationcode() {
		return this.informationcode;
	}

	/**
	 * Set the 银行代码.
	 * 
	 * @param bankcode
	 *            银行代码
	 */
	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	/**
	 * Get the 银行代码.
	 * 
	 * @return 银行代码
	 */
	public String getBankcode() {
		return this.bankcode;
	}

	/**
	 * Set the 账号.
	 * 
	 * @param paymentaccount
	 *            账号
	 */
	public void setPaymentaccount(String paymentaccount) {
		this.paymentaccount = paymentaccount;
	}

	/**
	 * Get the 账号.
	 * 
	 * @return 账号
	 */
	public String getPaymentaccount() {
		return this.paymentaccount;
	}

	/**
	 * Set the 户名.
	 * 
	 * @param accountname
	 *            户名
	 */
	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	/**
	 * Get the 户名.
	 * 
	 * @return 户名
	 */
	public String getAccountname() {
		return this.accountname;
	}

	/**
	 * Set the 开户行.
	 * 
	 * @param openningbank
	 *            开户行
	 */
	public void setOpenningbank(String openningbank) {
		this.openningbank = openningbank;
	}

	/**
	 * Get the 开户行.
	 * 
	 * @return 开户行
	 */
	public String getOpenningbank() {
		return this.openningbank;
	}

	/**
	 * Set the 电话.
	 * 
	 * @param phonenumber
	 *            电话
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	/**
	 * Get the 电话.
	 * 
	 * @return 电话
	 */
	public String getPhonenumber() {
		return this.phonenumber;
	}

	/**
	 * Set the QQ.
	 * 
	 * @param qq
	 *            QQ
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * Get the QQ.
	 * 
	 * @return QQ
	 */
	public String getQq() {
		return this.qq;
	}

	/**
	 * Set the skype.
	 * 
	 * @param skype
	 *            skype
	 */
	public void setSkype(String skype) {
		this.skype = skype;
	}

	/**
	 * Get the skype.
	 * 
	 * @return skype
	 */
	public String getSkype() {
		return this.skype;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 员工信息备注.
	 * 
	 * @param infomationcomment
	 *            员工信息备注
	 */
	public void setInfomationcomment(String infomationcomment) {
		this.infomationcomment = infomationcomment;
	}

	/**
	 * Get the 员工信息备注.
	 * 
	 * @return 员工信息备注
	 */
	public String getInfomationcomment() {
		return this.infomationcomment;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((informationcode == null) ? 0 : informationcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseEmployeeInformation other = (EnterpriseEmployeeInformation) obj;
		if (informationcode == null) {
			if (other.informationcode != null) {
				return false;
			}
		} else if (!informationcode.equals(other.informationcode)) {
			return false;
		}
		return true;
	}

}
