package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Model class of enterprise_employee.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseEmployee implements Serializable {
	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	/** 员工编码. */
	private String employeecode;
	/** 企业编码 */
	private String enterprisecode;
	/** 品牌编码. */
	private String brandcode;
	/** 员工上级编码. */
	private String parentemployeecode;
	/** 员工上级账号 */
	private String parentemployeeaccount;
	/** 员工类别编码. */
	private String employeetypecode;
	/** 员工级别编码. */
	private String employeelevelcode;
	/** 登陆账号. */
	private String loginaccount;
	/** 登陆密码. */
	private String loginpassword;
	/** 登陆密码2，加密原始密码. */
	private String loginpassword2;
	/** 资金密码 */
	private String fundpassword;
	/** 显示别名. */
	private String displayalias;
	/** 在线状态. */
	private Byte onlinestatus;
	/** 员工状态. */
	private Byte employeestatus;
	/** 注册时间. */
	private Date logindatetime;
	/**最后登录时间*/
	private Date lastlogintime;
	/** 分红 */
	private BigDecimal dividend;
	/** 占成 */
	private BigDecimal share;
	/** 会员信用评级 */
	private Byte creditrating;
	/** 注册链接编码 */
	private String registercode;
	/**	 数据状态	 */
	private String  datastatus;
	/** 用户直线代理数量统计  */
	private int agentCount;
	/** 用户直线会员数量统计  */
	private int memberCount;
	/** 用户来源统计  */
	private String domainlink;
	
	/**
	 * 手机号码，用于注册验证，并且必须是唯一，同手机号码不能注册多个用户
	 */
	private String phoneno;
	private String phonestatus;//0=未验证 1=已验证
	private String email;
	private String qq;
	private String wechat;
	private String alipay;
	
	/**
	 * IP白名单限制状态
	 */
	private String ipstatus;
	
	/*  开始时间 */
	private Date startDate;
	/*  结束时间 */
	private Date endDate;
	
	/* 视图属性：员工类别名称. */
	private String employeetypename;
	
	/* 视图属性：企业名称. */
	private String enterprisename;
	
	/* 视图属性：员工级别名称. */
	private String employeelevelname;
	/* 视图属性：员工级别排序. */
	private String employeelevelord;
	
	/* 视图属性：品牌名称. */
	private String brandname;
	
	/* 视图属性：账户余额 */
	private BigDecimal balance;
	
	/* 视图属性：累计存款 */
	private BigDecimal accumulateddeposit;
	
	/* 视图属性：累计提现 */
	private BigDecimal accumulatedwithdraw;
	
	/* 上级属性 */
	private String upperlevel;
	
	/*  加密的唯一标志列 */
	private String  sign;
	
	/**客户活跃度返回字段*/
	private String Days;
	private String num;
	
	/**用户输赢统计需要用到一下字段*/
	//洗码
	private BigDecimal bonus;
	//游戏投注金额
	private BigDecimal game_betting_amount;
	//输赢金额
	private BigDecimal lose_win_amount;
	//用户输赢金额
	private BigDecimal user_lose_win_amount;
	//利润金额
	private BigDecimal profit_amount;
	//游戏类型
	private String gametype;
	//游戏名称
	private String gamename;
	//api域名
	private String apiurl;
	
	public enum Enum_ipstatus{
		启用("1","启用"),
		禁用("2","禁用");
		public String value;
		public String desc;
		
		private Enum_ipstatus(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	public enum Enum_employeestatus{
		启用(1,"启用"),
		锁定游戏(2,"锁定游戏"),
		禁用(3,"禁用"),
		待激活(4,"待激活");
		public Integer value;
		public String desc;
		
		private Enum_employeestatus(Integer value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	public enum Enum_onlinestatus{
		离线("0","离线"),
		在线("1","在线");
		public String value;
		public String desc;
		
		private Enum_onlinestatus(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	public enum Enum_Creditrating {
		一星((byte)1),
		二星((byte)2),
		三星((byte)3),
		四星((byte)4),
		五星((byte)5);
		public byte value;
		private Enum_Creditrating(byte value) {
			this.value = value;
		}
		
	}
	public String getUpperlevel() {
		return upperlevel;
	}

	public void setUpperlevel(String upperlevel) {
		this.upperlevel = upperlevel;
	}

	public int getAgentCount() {
		return agentCount;
	}

	public void setAgentCount(int agentCount) {
		this.agentCount = agentCount;
	}

	public int getMemberCount() {
		return memberCount;
	}

	public void setMemberCount(int memberCount) {
		this.memberCount = memberCount;
	}

	public String getEnterprisename() {
		return enterprisename;
	}

	public void setEnterprisename(String enterprisename) {
		this.enterprisename = enterprisename;
	}
	
	public Date getLastlogintime() {
		return lastlogintime;
	}

	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}
	
	public String getEnterprisecode() {
		return enterprisecode;
	}

	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	public String getBrandcode() {
		return brandcode;
	}

	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}
	
	public String getEmployeetypename() {
		return employeetypename;
	}

	public void setEmployeetypename(String employeetypename) {
		this.employeetypename = employeetypename;
	}

	public String getEmployeelevelname() {
		return employeelevelname;
	}

	public void setEmployeelevelname(String employeelevelname) {
		this.employeelevelname = employeelevelname;
	}
	
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Constructor.
	 */
	public EnterpriseEmployee() {
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 员工上级编码.
	 * 
	 * @param parentemployeecode
	 *            员工上级编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	public String getParentemployeeaccount() {
		return parentemployeeaccount;
	}

	public void setParentemployeeaccount(String parentemployeeaccount) {
		this.parentemployeeaccount = parentemployeeaccount;
	}

	/**
	 * Get the 员工上级编码.
	 * 
	 * @return 员工上级编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 员工类别编码.
	 * 
	 * @param employeetypecode
	 *            员工类别编码
	 */
	public void setEmployeetypecode(String employeetypecode) {
		this.employeetypecode = employeetypecode;
	}

	/**
	 * Get the 员工类别编码.
	 * 
	 * @return 员工类别编码
	 */
	public String getEmployeetypecode() {
		return this.employeetypecode;
	}

	/**
	 * Set the 员工级别编码.
	 * 
	 * @param employeelevelcode
	 *            员工级别编码
	 */
	public void setEmployeelevelcode(String employeelevelcode) {
		this.employeelevelcode = employeelevelcode;
	}

	/**
	 * Get the 员工级别编码.
	 * 
	 * @return 员工级别编码
	 */
	public String getEmployeelevelcode() {
		return this.employeelevelcode;
	}

	/**
	 * Set the 登陆账号.
	 * 
	 * @param loginaccount
	 *            登陆账号
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 登陆账号.
	 * 
	 * @return 登陆账号
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 登陆密码.
	 * 
	 * @param loginpassword
	 *            登陆密码
	 */
	public void setLoginpassword(String loginpassword) {
		this.loginpassword = loginpassword;
	}

	/**
	 * Get the 登陆密码.
	 * 
	 * @return 登陆密码
	 */
	public String getLoginpassword() {
		return this.loginpassword;
	}

	public String getFundpassword() {
		return fundpassword;
	}

	public void setFundpassword(String fundpassword) {
		this.fundpassword = fundpassword;
	}

	/**
	 * Set the 显示别名.
	 * 
	 * @param displayalias
	 *            显示别名
	 */
	public void setDisplayalias(String displayalias) {
		this.displayalias = displayalias;
	}

	/**
	 * Get the 显示别名.
	 * 
	 * @return 显示别名
	 */
	public String getDisplayalias() {
		return this.displayalias;
	}

	/**
	 * Set the 在线状态.
	 * 
	 * @param onlinestatus
	 * 在线状态
	 * { 0 : 未登录 ,1 : 在线 , 2 : 下线}
	 */
	public void setOnlinestatus(Byte onlinestatus) {
		this.onlinestatus = onlinestatus;
	}

	/**
	 * Get the 在线状态.
	 * 
	 * @return 在线状态
	 */
	public Byte getOnlinestatus() {
		return this.onlinestatus;
	}

	/**
	 * Set the 员工状态.
	 * 
	 * @param employeestatus
	 *            员工状态
	 *  {0:逻辑删除,1: 启用, 2:锁定游戏,4: 禁用}
	 */
	public void setEmployeestatus(Byte employeestatus) {
		this.employeestatus = employeestatus;
	}

	public BigDecimal getProfit_amount() {
		return profit_amount;
	}

	public void setProfit_amount(BigDecimal profit_amount) {
		this.profit_amount = profit_amount;
	}

	/**
	 * Get the 员工状态.
	 * 
	 * @return 员工状态
	 */
	public Byte getEmployeestatus() {
		return this.employeestatus;
	}

	/**
	 * Set the 注册时间.
	 * 
	 * @param logindatetime
	 *            注册时间
	 */
	public void setLogindatetime(Date logindatetime) {
		this.logindatetime = logindatetime;
	}

	/**
	 * Get the 注册时间.
	 * 
	 * @return 注册时间
	 */
	public Date getLogindatetime() {
		return this.logindatetime;
	}

	public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public BigDecimal getDividend() {
		return dividend;
	}

	public void setDividend(BigDecimal dividend) {
		this.dividend = dividend;
	}

	public BigDecimal getShare() {
		return share;
	}

	public void setShare(BigDecimal share) {
		this.share = share;
	}

	public Byte getCreditrating() {
		return creditrating;
	}

	public void setCreditrating(Byte creditrating) {
		this.creditrating = creditrating;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getDatastatus() {
		return datastatus;
	}

	public void setDatastatus(String datastatus) {
		this.datastatus = datastatus;
	}

	public String getRegistercode() {
		return registercode;
	}

	public void setRegistercode(String registercode) {
		this.registercode = registercode;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getAccumulateddeposit() {
		return accumulateddeposit;
	}

	public void setAccumulateddeposit(BigDecimal accumulateddeposit) {
		this.accumulateddeposit = accumulateddeposit;
	}

	public BigDecimal getAccumulatedwithdraw() {
		return accumulatedwithdraw;
	}

	public void setAccumulatedwithdraw(BigDecimal accumulatedwithdraw) {
		this.accumulatedwithdraw = accumulatedwithdraw;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getDays() {
		return Days;
	}

	public void setDays(String days) {
		Days = days;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public BigDecimal getBonus() {
		return bonus;
	}

	public void setBonus(BigDecimal bonus) {
		this.bonus = bonus;
	}

	public BigDecimal getGame_betting_amount() {
		return game_betting_amount;
	}

	public void setGame_betting_amount(BigDecimal game_betting_amount) {
		this.game_betting_amount = game_betting_amount;
	}

	public BigDecimal getLose_win_amount() {
		return lose_win_amount;
	}

	public void setLose_win_amount(BigDecimal lose_win_amount) {
		this.lose_win_amount = lose_win_amount;
	}

	public BigDecimal getUser_lose_win_amount() {
		return user_lose_win_amount;
	}

	public void setUser_lose_win_amount(BigDecimal user_lose_win_amount) {
		this.user_lose_win_amount = user_lose_win_amount;
	}

	public String getDomainlink() {
		return domainlink;
	}

	public void setDomainlink(String domainlink) {
		this.domainlink = domainlink;
	}

	public String getGametype() {
		return gametype;
	}

	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	public String getGamename() {
		return gamename;
	}

	public void setGamename(String gamename) {
		this.gamename = gamename;
	}

	public String getApiurl() {
		return apiurl;
	}

	public void setApiurl(String apiurl) {
		this.apiurl = apiurl;
	}

	public String getLoginpassword2() {
		return loginpassword2;
	}

	public void setLoginpassword2(String loginpassword2) {
		this.loginpassword2 = loginpassword2;
	}

	public String getPhoneno() {
		return phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	public String getIpstatus() {
		return ipstatus;
	}

	public void setIpstatus(String ipstatus) {
		this.ipstatus = ipstatus;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getWechat() {
		return wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public String getEmployeelevelord() {
		return employeelevelord;
	}

	public void setEmployeelevelord(String employeelevelord) {
		this.employeelevelord = employeelevelord;
	}

	public String getAlipay() {
		return alipay;
	}

	public void setAlipay(String alipay) {
		this.alipay = alipay;
	}

	public String getPhonestatus() {
		return phonestatus;
	}

	public void setPhonestatus(String phonestatus) {
		this.phonestatus = phonestatus;
	}
	

}
