package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of enterprise_brand_activity.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseBrandActivity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer enterprisebrandactivitycode;

	/** 企业编码. */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;

	/** 团队编码. */
	private String employeecode;

	/** 定制活动编码. */
	private Integer ecactivitycode;

	/** 活动开始时间. */
	private Date begintime;

	/** 活动结束时间. */
	private Date endtime;

	/** 活动状态. */
	private String status;
	
	
	/* 加密唯一标识列 */
	private String sign;
	
	/* 企业名称 */
	private String enterprisename;
	
	/* 品牌名称 */
	private String brandname;
	
	/* 登陆账号 */
	private String loginaccount;
	
	/* 活动名称 */
	private String activityname;
	
	/* 活动类型 0为普通 1为特殊 */
	private Integer activitynature;
	
	/* 活动图片 */
	private String activityimage;
	
	/* 活动内容 */
	private String activitycontent;
	
	
	public enum Enum_status{
		启用("1","启用"),
		禁用("2","禁用");
		public String value;
		public String desc;
		
		private Enum_status(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	/**
	 * API返回brand参数对象
	 * @author king
	 *
	 */
	public class ApiBrandParameter{
		private String agementdesc; //参数介绍
		private String agementname; //参数名称
		private String agementvalue; //参数值
		
		public String getAgementdesc() {
			return agementdesc;
		}
		public void setAgementdesc(String agementdesc) {
			this.agementdesc = agementdesc;
		}
		public String getAgementname() {
			return agementname;
		}
		public void setAgementname(String agementname) {
			this.agementname = agementname;
		}
		public String getAgementvalue() {
			return agementvalue;
		}
		public void setAgementvalue(String agementvalue) {
			this.agementvalue = agementvalue;
		}
		
	}

	/**
	 * Constructor.
	 */
	public EnterpriseBrandActivity() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param enterprisebrandactivitycode
	 *            主键
	 */
	public void setEnterprisebrandactivitycode(Integer enterprisebrandactivitycode) {
		this.enterprisebrandactivitycode = enterprisebrandactivitycode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getEnterprisebrandactivitycode() {
		return this.enterprisebrandactivitycode;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 团队编码.
	 * 
	 * @param employeecode
	 *            团队编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 团队编码.
	 * 
	 * @return 团队编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 活动编码.
	 * 
	 * @param activitycode
	 *            活动编码
	 */
	public void setEcactivitycode(Integer ecactivitycode) {
		this.ecactivitycode = ecactivitycode;
	}

	/**
	 * Get the 活动编码.
	 * 
	 * @return 活动编码
	 */
	public Integer getEcactivitycode() {
		return this.ecactivitycode;
	}

	/**
	 * Set the 活动开始时间.
	 * 
	 * @param begintime
	 *            活动开始时间
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * Get the 活动开始时间.
	 * 
	 * @return 活动开始时间
	 */
	public Date getBegintime() {
		return this.begintime;
	}

	/**
	 * Set the 活动结束时间.
	 * 
	 * @param endtime
	 *            活动结束时间
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * Get the 活动结束时间.
	 * 
	 * @return 活动结束时间
	 */
	public Date getEndtime() {
		return this.endtime;
	}

	/**
	 * Set the 活动状态.
	 * 
	 * @param status
	 *            活动状态
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the 活动状态.
	 * 
	 * @return 活动状态
	 */
	public String getStatus() {
		return this.status;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getEnterprisename() {
		return enterprisename;
	}

	public void setEnterprisename(String enterprisename) {
		this.enterprisename = enterprisename;
	}

	public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public String getLoginaccount() {
		return loginaccount;
	}

	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	public String getActivityname() {
		return activityname;
	}

	public void setActivityname(String activityname) {
		this.activityname = activityname;
	}

	public Integer getActivitynature() {
		return activitynature;
	}

	public void setActivitynature(Integer activitynature) {
		this.activitynature = activitynature;
	}

	public String getActivityimage() {
		return activityimage;
	}

	public void setActivityimage(String activityimage) {
		this.activityimage = activityimage;
	}

	public String getActivitycontent() {
		return activitycontent;
	}

	public void setActivitycontent(String activitycontent) {
		this.activitycontent = activitycontent;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((enterprisebrandactivitycode == null) ? 0 : enterprisebrandactivitycode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseBrandActivity other = (EnterpriseBrandActivity) obj;
		if (enterprisebrandactivitycode == null) {
			if (other.enterprisebrandactivitycode != null) {
				return false;
			}
		} else if (!enterprisebrandactivitycode.equals(other.enterprisebrandactivitycode)) {
			return false;
		}
		return true;
	}


}
