package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of enterprise_operating_brand_pay.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseOperatingBrandPay implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** lsh. */
	private Integer lsh;

	/** enterprisecode. */
	private String enterprisecode;

	/** brandcode. */
	private String brandcode;

	/** paycallbackurl. */
	private String paycallbackurl;
	
	/** adminurl. */
	private String adminurl;

	/** datastatus. */
	private Integer datastatus;

	
	//
	private String brandname;
	//
	private String sign;
	
	
	public enum Enum_Datastatus{
		无效(0,"无效"),
    	有效(1,"有效"),
    	;
    	
    	public int value;
    	public String desc;
    	private Enum_Datastatus(int _value,String _desc){
    		this.value=_value;
    		this.desc=_desc;
    	}
    	
    }
	
	/**
	 * Constructor.
	 */
	public EnterpriseOperatingBrandPay() {
	}

	/**
	 * Set the lsh.
	 * 
	 * @param lsh
	 *            lsh
	 */
	public void setLsh(Integer lsh) {
		this.lsh = lsh;
	}

	/**
	 * Get the lsh.
	 * 
	 * @return lsh
	 */
	public Integer getLsh() {
		return this.lsh;
	}

	/**
	 * Set the enterprisecode.
	 * 
	 * @param enterprisecode
	 *            enterprisecode
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the enterprisecode.
	 * 
	 * @return enterprisecode
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the brandcode.
	 * 
	 * @param brandcode
	 *            brandcode
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the brandcode.
	 * 
	 * @return brandcode
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the paycallbackurl.
	 * 
	 * @param paycallbackurl
	 *            paycallbackurl
	 */
	public void setPaycallbackurl(String paycallbackurl) {
		this.paycallbackurl = paycallbackurl;
	}

	/**
	 * Get the paycallbackurl.
	 * 
	 * @return paycallbackurl
	 */
	public String getPaycallbackurl() {
		return this.paycallbackurl;
	}

	/**
	 * Set the datastatus.
	 * 
	 * @param datastatus
	 *            datastatus
	 */
	public void setDatastatus(Integer datastatus) {
		this.datastatus = datastatus;
	}

	/**
	 * Get the datastatus.
	 * 
	 * @return datastatus
	 */
	public Integer getDatastatus() {
		return this.datastatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lsh == null) ? 0 : lsh.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseOperatingBrandPay other = (EnterpriseOperatingBrandPay) obj;
		if (lsh == null) {
			if (other.lsh != null) {
				return false;
			}
		} else if (!lsh.equals(other.lsh)) {
			return false;
		}
		return true;
	}

	public String getAdminurl() {
		return adminurl;
	}

	public void setAdminurl(String adminurl) {
		this.adminurl = adminurl;
	}

	public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

}
