package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of enterprise_operating_brand_game.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseOperatingBrandGame implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 游戏编码. */
	private String gamecode;
	
	/** 品牌编码. */
	private String brandcode;
	
	/** 标记 客户操作此字段来实现游戏的暂停或开启（如果为0的情况下，程序会对其进行检查并实时更新状态，反之不检查）*/
    private Integer flag;//
    
    //视图字段
    private String gamename;

	/**
	 * 空构造方法
	 */
	public EnterpriseOperatingBrandGame() {
	}
	/**
	 * 带参数构造方法
	 */
	public EnterpriseOperatingBrandGame(String brandcode,String gamecode, int flag) {
		this.brandcode = brandcode;
		this.gamecode = gamecode;
		this.flag = flag;
	}
	public EnterpriseOperatingBrandGame(String brandcode) {
		this.brandcode = brandcode;
	}
	public EnterpriseOperatingBrandGame(String brandcode,Integer flag) {
		this.brandcode = brandcode;
		this.flag = flag;
	}
	
	public enum Enum_flag{
    	正常(0,"正常"),
    	停用(1,"停用"),
    	维护(2,"维护");
    	public Integer value;
    	public String desc;
    	private Enum_flag(Integer _value,String _desc){
    		this.value = _value;
    		this.desc = _desc;
    	}
    }
	
	
	
	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Get the 游戏编码
	 * @return 游戏编码
	 */
	public String getGamecode() {
		return gamecode;
	}
	
	/**
	 * Set the　游戏编码
	 * @param 游戏编码
	 */
	public void setGamecode(String gamecode) {
		this.gamecode = gamecode;
	}

	public Integer getFlag() {
		return flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}
	public String getGamename() {
		return gamename;
	}
	public void setGamename(String gamename) {
		this.gamename = gamename;
	}
}
