package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of enterprise_thirdparty_payment_agument.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnterpriseThirdpartyPaymentAgument implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer paymentagumentcode;

	/** 企业第三方支付编码. */
	private String enterprisethirdpartycode;
	
	/** 第三方支付参数编码. */
	private String paymentsettingcode;
	
	/** 参数值. */
	private String agumentvalue;
	
	/* 关联属性：参数描述*/
	private String argumentdesc;
	
	/* 关联属性:企业第三方支付描述. */
	private String dscription;

	/* 关联属性:支付类型名称*/
	private String thirdpartypaymenttypename;
	
	/* 关联属性：参数字段名 */
	private String argumentfiled;
	
	/* 关联属性：第三方支付类型编码 */
	private String thirdpartypaymenttypecode;
	
	
	public String getThirdpartypaymenttypename() {
		return thirdpartypaymenttypename;
	}

	public void setThirdpartypaymenttypename(String thirdpartypaymenttypename) {
		this.thirdpartypaymenttypename = thirdpartypaymenttypename;
	}

	public String getArgumentdesc() {
		return argumentdesc;
	}

	public void setArgumentdesc(String argumentdesc) {
		this.argumentdesc = argumentdesc;
	}
	
	public String getDscription() {
		return dscription;
	}

	public void setDscription(String dscription) {
		this.dscription = dscription;
	}
	
	/**
	 * Constructor.
	 */
	public EnterpriseThirdpartyPaymentAgument() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param paymentagumentcode
	 *            主键
	 */
	public void setPaymentagumentcode(Integer paymentagumentcode) {
		this.paymentagumentcode = paymentagumentcode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getPaymentagumentcode() {
		return this.paymentagumentcode;
	}

	/**
	 * Set the 企业第三方支付编码.
	 * 
	 * @param enterprisethirdpartycode
	 *            企业第三方支付编码
	 */
	public void setEnterprisethirdpartycode(String enterprisethirdpartycode) {
		this.enterprisethirdpartycode = enterprisethirdpartycode;
	}

	/**
	 * Get the 企业第三方支付编码.
	 * 
	 * @return 企业第三方支付编码
	 */
	public String getEnterprisethirdpartycode() {
		return this.enterprisethirdpartycode;
	}

	/**
	 * Set the 第三方支付参数编码.
	 * 
	 * @param paymentsettingcode
	 *            第三方支付参数编码
	 */
	public void setPaymentsettingcode(String paymentsettingcode) {
		this.paymentsettingcode = paymentsettingcode;
	}

	/**
	 * Get the 第三方支付参数编码.
	 * 
	 * @return 第三方支付参数编码
	 */
	public String getPaymentsettingcode() {
		return this.paymentsettingcode;
	}

	/**
	 * Set the 参数值.
	 * 
	 * @param agumentvalue
	 *            参数值
	 */
	public void setAgumentvalue(String agumentvalue) {
		this.agumentvalue = agumentvalue;
	}

	/**
	 * Get the 参数值.
	 * 
	 * @return 参数值
	 */
	public String getAgumentvalue() {
		return this.agumentvalue;
	}

	public String getArgumentfiled() {
		return argumentfiled;
	}

	public void setArgumentfiled(String argumentfiled) {
		this.argumentfiled = argumentfiled;
	}

	public String getThirdpartypaymenttypecode() {
		return thirdpartypaymenttypecode;
	}

	public void setThirdpartypaymenttypecode(String thirdpartypaymenttypecode) {
		this.thirdpartypaymenttypecode = thirdpartypaymenttypecode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((paymentagumentcode == null) ? 0 : paymentagumentcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnterpriseThirdpartyPaymentAgument other = (EnterpriseThirdpartyPaymentAgument) obj;
		if (paymentagumentcode == null) {
			if (other.paymentagumentcode != null) {
				return false;
			}
		} else if (!paymentagumentcode.equals(other.paymentagumentcode)) {
			return false;
		}
		return true;
	}

}
