package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of game_platform_prefix.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GamePlatformPrefix implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer lsh;

	/** 企业编码. */
	private String enterprisecode;

	/** 游戏平台. */
	private String gamePlatform;

	/** 前缀. */
	private String prefixcode;

	/**
	 * Constructor.
	 */
	public GamePlatformPrefix() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param lsh
	 *            主键
	 */
	public void setLsh(Integer lsh) {
		this.lsh = lsh;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getLsh() {
		return this.lsh;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 游戏平台.
	 * 
	 * @param gamePlatform
	 *            游戏平台
	 */
	public void setGamePlatform(String gamePlatform) {
		this.gamePlatform = gamePlatform;
	}

	/**
	 * Get the 游戏平台.
	 * 
	 * @return 游戏平台
	 */
	public String getGamePlatform() {
		return this.gamePlatform;
	}

	/**
	 * Set the 前缀.
	 * 
	 * @param prefixcode
	 *            前缀
	 */
	public void setPrefixcode(String prefixcode) {
		this.prefixcode = prefixcode;
	}

	/**
	 * Get the 前缀.
	 * 
	 * @return 前缀
	 */
	public String getPrefixcode() {
		return this.prefixcode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lsh == null) ? 0 : lsh.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GamePlatformPrefix other = (GamePlatformPrefix) obj;
		if (lsh == null) {
			if (other.lsh != null) {
				return false;
			}
		} else if (!lsh.equals(other.lsh)) {
			return false;
		}
		return true;
	}

}
