package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Model class of game_category.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GameCategory implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 游戏种类编码. */
	private Integer categorycode;

	/** 游戏平台标志(唯一). */
	private String gametype;

	/** 游戏种类类型标志(唯一). */
	private String categorytype;

	/** 游戏种类名称. */
	private String categoryname;

	/** 最小洗码值. */
	private BigDecimal minbonus;

	/** 最大洗码值. */
	private BigDecimal maxbonus;

	/** 排序. */
	private Short sort;

	/**
	 * Constructor.
	 */
	public GameCategory() {
	}
	
	public GameCategory(String gametype,String categorytype){
		this.gametype = gametype;
		this.categorytype = categorytype;
	}

	/**
	 * Set the 游戏种类编码.
	 * 
	 * @param categorycode
	 *            游戏种类编码
	 */
	public void setCategorycode(Integer categorycode) {
		this.categorycode = categorycode;
	}

	/**
	 * Get the 游戏种类编码.
	 * 
	 * @return 游戏种类编码
	 */
	public Integer getCategorycode() {
		return this.categorycode;
	}

	/**
	 * Set the 游戏平台标志(唯一).
	 * 
	 * @param gametype
	 *            游戏平台标志(唯一)
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏平台标志(唯一).
	 * 
	 * @return 游戏平台标志(唯一)
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 游戏种类类型标志(唯一).
	 * 
	 * @param categorytype
	 *            游戏种类类型标志(唯一)
	 */
	public void setCategorytype(String categorytype) {
		this.categorytype = categorytype;
	}

	/**
	 * Get the 游戏种类类型标志(唯一).
	 * 
	 * @return 游戏种类类型标志(唯一)
	 */
	public String getCategorytype() {
		return this.categorytype;
	}

	/**
	 * Set the 游戏种类名称.
	 * 
	 * @param categoryname
	 *            游戏种类名称
	 */
	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
	 * Get the 游戏种类名称.
	 * 
	 * @return 游戏种类名称
	 */
	public String getCategoryname() {
		return this.categoryname;
	}

	/**
	 * Set the 最小洗码值.
	 * 
	 * @param minbonus
	 *            最小洗码值
	 */
	public void setMinbonus(BigDecimal minbonus) {
		this.minbonus = minbonus;
	}

	/**
	 * Get the 最小洗码值.
	 * 
	 * @return 最小洗码值
	 */
	public BigDecimal getMinbonus() {
		return this.minbonus;
	}

	/**
	 * Set the 最大洗码值.
	 * 
	 * @param maxbonus
	 *            最大洗码值
	 */
	public void setMaxbonus(BigDecimal maxbonus) {
		this.maxbonus = maxbonus;
	}

	/**
	 * Get the 最大洗码值.
	 * 
	 * @return 最大洗码值
	 */
	public BigDecimal getMaxbonus() {
		return this.maxbonus;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param order
	 *            排序
	 */
	public void setSort(Short sort) {
		this.sort = sort;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Short getSort() {
		return this.sort;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((categorycode == null) ? 0 : categorycode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GameCategory other = (GameCategory) obj;
		if (categorycode == null) {
			if (other.categorycode != null) {
				return false;
			}
		} else if (!categorycode.equals(other.categorycode)) {
			return false;
		}
		return true;
	}

}
