package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of game_class_details.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GameClassDetails implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 分类明细编码,主键. */
	private Integer classdetailscode;

	/** 分类编码. */
	private String gameclasscode;

	/** 游戏flag,对应各个平台的游戏编码. */
	private String classdetailsflag;

	/** 游戏中文名. */
	private String detailschinaname;

	/** 游戏英文名. */
	private String detailsenglishname;

	/** 图片名称. */
	private String picturename;

	/** 服务器存储路径. */
	private String path;

	/** 排序. */
	private Short sort;

	/** 是否可用(1:可用，2:不可用). */
	private String disable;

	/**
	 * Constructor.
	 */
	public GameClassDetails() {
	}

	/**
	 * Set the 分类明细编码,主键.
	 * 
	 * @param classdetailscode
	 *            分类明细编码,主键
	 */
	public void setClassdetailscode(Integer classdetailscode) {
		this.classdetailscode = classdetailscode;
	}

	/**
	 * Get the 分类明细编码,主键.
	 * 
	 * @return 分类明细编码,主键
	 */
	public Integer getClassdetailscode() {
		return this.classdetailscode;
	}

	/**
	 * Set the 分类编码.
	 * 
	 * @param gameclasscode
	 *            分类编码
	 */
	public void setGameclasscode(String gameclasscode) {
		this.gameclasscode = gameclasscode;
	}

	/**
	 * Get the 分类编码.
	 * 
	 * @return 分类编码
	 */
	public String getGameclasscode() {
		return this.gameclasscode;
	}

	/**
	 * Set the 游戏flag,对应各个平台的游戏编码.
	 * 
	 * @param classdetailsflag
	 *            游戏flag,对应各个平台的游戏编码
	 */
	public void setClassdetailsflag(String classdetailsflag) {
		this.classdetailsflag = classdetailsflag;
	}

	/**
	 * Get the 游戏flag,对应各个平台的游戏编码.
	 * 
	 * @return 游戏flag,对应各个平台的游戏编码
	 */
	public String getClassdetailsflag() {
		return this.classdetailsflag;
	}

	/**
	 * Set the 游戏中文名.
	 * 
	 * @param detailschinaname
	 *            游戏中文名
	 */
	public void setDetailschinaname(String detailschinaname) {
		this.detailschinaname = detailschinaname;
	}

	/**
	 * Get the 游戏中文名.
	 * 
	 * @return 游戏中文名
	 */
	public String getDetailschinaname() {
		return this.detailschinaname;
	}

	/**
	 * Set the 游戏英文名.
	 * 
	 * @param detailsenglishname
	 *            游戏英文名
	 */
	public void setDetailsenglishname(String detailsenglishname) {
		this.detailsenglishname = detailsenglishname;
	}

	/**
	 * Get the 游戏英文名.
	 * 
	 * @return 游戏英文名
	 */
	public String getDetailsenglishname() {
		return this.detailsenglishname;
	}

	/**
	 * Set the 图片名称.
	 * 
	 * @param pricturename
	 *            图片名称
	 */
	public void setPicturename(String picturename) {
		this.picturename = picturename;
	}

	/**
	 * Get the 图片名称.
	 * 
	 * @return 图片名称
	 */
	public String getPicturename() {
		return this.picturename;
	}

	/**
	 * Set the 服务器存储路径.
	 * 
	 * @param path
	 *            服务器存储路径
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * Get the 服务器存储路径.
	 * 
	 * @return 服务器存储路径
	 */
	public String getPath() {
		return this.path;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param sort
	 *            排序
	 */
	public void setSort(Short sort) {
		this.sort = sort;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Short getSort() {
		return this.sort;
	}

	/**
	 * Set the 是否可用(1:可用，2:不可用).
	 * 
	 * @param disable
	 *            是否可用(1:可用，2:不可用)
	 */
	public void setDisable(String disable) {
		this.disable = disable;
	}

	/**
	 * Get the 是否可用(1:可用，2:不可用).
	 * 
	 * @return 是否可用(1:可用，2:不可用)
	 */
	public String getDisable() {
		return this.disable;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classdetailscode == null) ? 0 : classdetailscode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GameClassDetails other = (GameClassDetails) obj;
		if (classdetailscode == null) {
			if (other.classdetailscode != null) {
				return false;
			}
		} else if (!classdetailscode.equals(other.classdetailscode)) {
			return false;
		}
		return true;
	}

}
