package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of game_api_input.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GameApiInput implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 接口编码. */
	private String apicode;

	/** 平台编码. */
	private String platformcode;
	
	/** 品牌编码 */
	private String enterprisecode;

	/** 接口地址. */
	private String apiurl;

	/** 接口状态. */
	private Byte outputapistatus;

	/** 接口key1. */
	private String apikey1;

	/** 接口key2. */
	private String apikey2;

	/** 接口用户. */
	private String apiuser;

	/** 接口用户密码. */
	private String apipassword;

	/** 接口备注. */
	private String apicomment;
	
	/** 接口尝试连接次数 */
	private Integer trytime = 1;
	
	/**
	 * Constructor.
	 */
	public GameApiInput() {
	}

	/**
	 * Set the 接口编码.
	 * 
	 * @param apicode
	 *            接口编码
	 */
	public void setApicode(String apicode) {
		this.apicode = apicode;
	}

	/**
	 * Get the 接口编码.
	 * 
	 * @return 接口编码
	 */
	public String getApicode() {
		return this.apicode;
	}

	/**
	 * Set the 游戏编码.
	 * 
	 * @param platformcode
	 *            游戏编码
	 */
	public void setPlatformcode(String platformcode) {
		this.platformcode = platformcode;
	}

	/**
	 * Get the 平台编码
	 * 
	 * @return 平台编码
	 */
	public String getPlatformcode() {
		return this.platformcode;
	}


	/**
	 * Get the 企业编码
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return enterprisecode;
	}

	/**
	 * Set the 企业编码
	 * @param 企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Set the 接口地址.
	 * 
	 * @param apiurl
	 *            接口地址
	 */
	public void setApiurl(String apiurl) {
		this.apiurl = apiurl;
	}

	/**
	 * Get the 接口地址.
	 * 
	 * @return 接口地址
	 */
	public String getApiurl() {
		return this.apiurl;
	}

	/**
	 * Set the 接口状态.
	 * 
	 * @param outputapistatus
	 *            接口状态
	 */
	public void setOutputapistatus(Byte outputapistatus) {
		this.outputapistatus = outputapistatus;
	}

	/**
	 * Get the 接口状态.
	 * 
	 * @return 接口状态
	 */
	public Byte getOutputapistatus() {
		return this.outputapistatus;
	}

	/**
	 * Set the 接口key1.
	 * 
	 * @param apikey1
	 *            接口key1
	 */
	public void setApikey1(String apikey1) {
		this.apikey1 = apikey1;
	}

	/**
	 * Get the 接口key1.
	 * 
	 * @return 接口key1
	 */
	public String getApikey1() {
		return this.apikey1;
	}

	/**
	 * Set the 接口key2.
	 * 
	 * @param apikey2
	 *            接口key2
	 */
	public void setApikey2(String apikey2) {
		this.apikey2 = apikey2;
	}

	/**
	 * Get the 接口key2.
	 * 
	 * @return 接口key2
	 */
	public String getApikey2() {
		return this.apikey2;
	}

	/**
	 * Set the 接口用户.
	 * 
	 * @param apiuser
	 *            接口用户
	 */
	public void setApiuser(String apiuser) {
		this.apiuser = apiuser;
	}

	/**
	 * Get the 接口用户.
	 * 
	 * @return 接口用户
	 */
	public String getApiuser() {
		return this.apiuser;
	}

	/**
	 * Set the 接口用户密码.
	 * 
	 * @param apipassword
	 *            接口用户密码
	 */
	public void setApipassword(String apipassword) {
		this.apipassword = apipassword;
	}

	/**
	 * Get the 接口用户密码.
	 * 
	 * @return 接口用户密码
	 */
	public String getApipassword() {
		return this.apipassword;
	}

	/**
	 * Set the 接口备注.
	 * 
	 * @param apicomment
	 *            接口备注
	 */
	public void setApicomment(String apicomment) {
		this.apicomment = apicomment;
	}

	/**
	 * Get the 接口备注.
	 * 
	 * @return 接口备注
	 */
	public String getApicomment() {
		return this.apicomment;
	}

	public Integer getTrytime() {
		return trytime;
	}

	public void setTrytime(Integer trytime) {
		this.trytime = trytime;
	}
	

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((apicode == null) ? 0 : apicode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GameApiInput other = (GameApiInput) obj;
		if (apicode == null) {
			if (other.apicode != null) {
				return false;
			}
		} else if (!apicode.equals(other.apicode)) {
			return false;
		}
		return true;
	}

	

}
