package com.maven.entity;

import java.io.Serializable;
import java.util.List;

/**
 * Model class of game_class.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GameClass implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** gameclasscode. */
	private Integer gameclasscode;

	/** 游戏类型(BBINGame,AGGame...). */
	private String gametype;

	/** 游戏分类名称(中文). */
	private String classchinaname;

	/** 游戏分类名称(英文). */
	private String classenglishname;

	/** 父级分类类型(自定义...). */
	private String parentclasstype;

	/** 排序. */
	private String sort;
	
	/* 下级菜单集合 */
	private List<GameClass> children;

	/**
	 * Constructor.
	 */
	public GameClass() {
	}

	/**
	 * Set the gameclasscode.
	 * 
	 * @param gameclasscode
	 *            gameclasscode
	 */
	public void setGameclasscode(Integer gameclasscode) {
		this.gameclasscode = gameclasscode;
	}

	/**
	 * Get the gameclasscode.
	 * 
	 * @return gameclasscode
	 */
	public Integer getGameclasscode() {
		return this.gameclasscode;
	}

	/**
	 * Set the 游戏类型(BBINGame,AGGame...).
	 * 
	 * @param gametype
	 *            游戏类型(BBINGame,AGGame...)
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏类型(BBINGame,AGGame...).
	 * 
	 * @return 游戏类型(BBINGame,AGGame...)
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 游戏分类名称(中文).
	 * 
	 * @param classchinaname
	 *            游戏分类名称(中文)
	 */
	public void setClasschinaname(String classchinaname) {
		this.classchinaname = classchinaname;
	}

	/**
	 * Get the 游戏分类名称(中文).
	 * 
	 * @return 游戏分类名称(中文)
	 */
	public String getClasschinaname() {
		return this.classchinaname;
	}

	/**
	 * Set the 游戏分类名称(英文).
	 * 
	 * @param classenglishname
	 *            游戏分类名称(英文)
	 */
	public void setClassenglishname(String classenglishname) {
		this.classenglishname = classenglishname;
	}

	/**
	 * Get the 游戏分类名称(英文).
	 * 
	 * @return 游戏分类名称(英文)
	 */
	public String getClassenglishname() {
		return this.classenglishname;
	}

	/**
	 * Set the 父级分类类型(自定义...).
	 * 
	 * @param parentclasstype
	 *            父级分类类型(自定义...)
	 */
	public void setParentclasstype(String parentclasstype) {
		this.parentclasstype = parentclasstype;
	}

	/**
	 * Get the 父级分类类型(自定义...).
	 * 
	 * @return 父级分类类型(自定义...)
	 */
	public String getParentclasstype() {
		return this.parentclasstype;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param sort
	 *            排序
	 */
	public void setSort(String sort) {
		this.sort = sort;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public String getSort() {
		return this.sort;
	}

	public List<GameClass> getChildren() {
		return children;
	}

	public void setChildren(List<GameClass> children) {
		this.children = children;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((gameclasscode == null) ? 0 : gameclasscode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GameClass other = (GameClass) obj;
		if (gameclasscode == null) {
			if (other.gameclasscode != null) {
				return false;
			}
		} else if (!gameclasscode.equals(other.gameclasscode)) {
			return false;
		}
		return true;
	}

}
