package com.maven.entity;

import java.io.Serializable;

/**
 * 企业登录白名单
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class LoginWhiteList implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private Integer lsh;

	/** 企业编码. */
	private String enterprisecode;

	/** 白名单IP. */
	private String ip;

	/** 备注. */
	private String remark;
	
	
	private String sign;

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * Constructor.
	 */
	public LoginWhiteList() {
	}

	/**
	 * Set the 编号.
	 * 
	 * @param lsh
	 *            编号
	 */
	public void setLsh(Integer lsh) {
		this.lsh = lsh;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public Integer getLsh() {
		return this.lsh;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 白名单IP.
	 * 
	 * @param ip
	 *            白名单IP
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * Get the 白名单IP.
	 * 
	 * @return 白名单IP
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param remark
	 *            备注
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getRemark() {
		return this.remark;
	}


}
