package com.maven.entity;

import java.io.Serializable;
import java.util.List;

/**
 * Model class of permission_menu.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PermissionMenu implements Serializable,Comparable<PermissionMenu>,Cloneable{

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** menucode. */
	private String menucode;

	/** 菜单标题. */
	private String menuname;
	
	/** 菜单英文标题 */
	private String englishname;

	/** 菜单访问URL. */
	private String menuurl;

	/** 排序. */
	private Integer menusort;

	/** 层级. */
	private Integer menulevel;

	/** 父菜单ID. */
	private String parentmenucode;

	/** 状态. */
	private Integer menustatus;
	
	/**  数据状态 */
	private String datastatus;
	
	/* 子菜单 */
	private List<PermissionMenu> children;
	
	/* 加密的唯一编码 */
	private String sign;
	
	/* 是否展开 */
	private Boolean expanded = false;
	
	/**
	 * Constructor.
	 */
	public PermissionMenu() {
	}
	
	/** 状态. */
	public enum Enum_menustatus{
		禁用(0,"禁用"),
		启用(1,"启用"),
		;
		public int value;
		public String desc;
		
		private Enum_menustatus(int value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	public enum Enum_language{
		中文("zh"),
		英文("en");
		public String value;
		
		private Enum_language(String value) {
			this.value = value;
		}
	}
	


	public String getMenucode() {
		return menucode;
	}


	public void setMenucode(String menucode) {
		this.menucode = menucode;
	}


	

	public List<PermissionMenu> getChildren() {
		return children;
	}

	public void setChildren(List<PermissionMenu> children) {
		this.children = children;
	}


	public String getSign() {
		return sign;
	}


	public void setSign(String sign) {
		this.sign = sign;
	}


	public String getMenuname() {
		return menuname;
	}


	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}


	public String getEnglishname() {
		return englishname;
	}


	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}


	public String getMenuurl() {
		return menuurl;
	}


	public void setMenuurl(String menuurl) {
		this.menuurl = menuurl;
	}


	public Integer getMenusort() {
		return menusort;
	}


	public void setMenusort(Integer menusort) {
		this.menusort = menusort;
	}


	public Integer getMenulevel() {
		return menulevel;
	}


	public void setMenulevel(Integer menulevel) {
		this.menulevel = menulevel;
	}


	public String getParentmenucode() {
		return parentmenucode;
	}


	public void setParentmenucode(String parentmenucode) {
		this.parentmenucode = parentmenucode;
	}


	public Integer getMenustatus() {
		return menustatus;
	}


	public void setMenustatus(Integer menustatus) {
		this.menustatus = menustatus;
	}


	public String getDatastatus() {
		return datastatus;
	}




	public void setDatastatus(String datastatus) {
		this.datastatus = datastatus;
	}




	public Boolean getExpanded() {
		return expanded;
	}


	public void setExpanded(Boolean expanded) {
		this.expanded = expanded;
	}


	@Override 
    public int compareTo(PermissionMenu arg0){ 
        if(this.menulevel.compareTo(arg0.menulevel) == 0) { 
            return this.menusort.compareTo(arg0.menusort); 
        }else{ 
            return this.menulevel.compareTo(arg0.menulevel); 
        } 
    }


	@Override
	public PermissionMenu clone() throws CloneNotSupportedException {
		return (PermissionMenu)super.clone();
	} 

}
