package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of report_weekly_agent.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportWeeklyAgent implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer reportcode;

	/** 企业编码. */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;

	/** 员工编码. */
	private String employeecode;

	/** 上级员工编码. */
	private String parentemployeecode;

	/** 用户账户. */
	private String loginaccount;

	/** 投注量. */
	private Double bet;

	/** 打码金额. */
	private Double amount;

	/** 需要减去的已发放金额. */
	private Double subtract;
	
	/** 实发金额.后台对补发记录，可以修改实发金额 */
	private Double actual;

	/** 打码比率. */
	private Double ratio;

	/** 打码开始日期. */
	private Date starttime;

	/** 打码结束日期. */
	private Date endtime;

	/** 报表日期. */
	private Date reporttime;

	/** 游戏平台. */
	private String gameplatform;

	/** 游戏类型. */
	private String gametype;
	
	/** 数据类型 1正常 2补发. */
	private String paytype;
	/***批次号。同一组数据的唯一编码，包括：员工编码、游戏平台、游戏类型、报表开始时间****/
	private String patchno;
	
	/** 打码发放状态 1未发放 2已发放. */
	private String status;
	
	/** 支付单号，可用于回滚事务. */
	private String payno;

	public enum Enum_status {
		未发放("1", "未发放"), 已发放("2", "已发放");
		public String value;
		public String desc;

		private Enum_status(String value, String desc) {
			this.value = value;
			this.desc = desc;
		}

		public static Enum_status getStatus(String status) {
			for (Enum_status e : Enum_status.values()) {
				if (e.value.endsWith("1"))
					return e;
			}
			return null;
		}
	}

	
	public enum Enum_paytype {
		正常("1", "正常"), 补发("2", "补发");
		public String value;
		public String desc;

		private Enum_paytype(String value, String desc) {
			this.value = value;
			this.desc = desc;
		}

		public static Enum_status getStatus(String status) {
			for (Enum_status e : Enum_status.values()) {
				if (e.value.endsWith("1"))
					return e;
			}
			return null;
		}
	}

	/**
	 * Constructor.
	 */
	public ReportWeeklyAgent() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param reportcode
	 *            主键
	 */
	public void setReportcode(Integer reportcode) {
		this.reportcode = reportcode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getReportcode() {
		return this.reportcode;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the 上级员工编码.
	 * 
	 * @param parentemployeecode
	 *            上级员工编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the 上级员工编码.
	 * 
	 * @return 上级员工编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账户.
	 * 
	 * @param loginaccount
	 *            用户账户
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账户.
	 * 
	 * @return 用户账户
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 投注量.
	 * 
	 * @param bet
	 *            投注量
	 */
	public void setBet(Double bet) {
		this.bet = bet;
	}

	/**
	 * Get the 投注量.
	 * 
	 * @return 投注量
	 */
	public Double getBet() {
		return this.bet;
	}

	/**
	 * Set the 打码金额.
	 * 
	 * @param amount
	 *            打码金额
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * Get the 打码金额.
	 * 
	 * @return 打码金额
	 */
	public Double getAmount() {
		return this.amount;
	}

	/**
	 * Set the 需要减去的已发放金额.
	 * 
	 * @param subtract
	 *            需要减去的已发放金额
	 */
	public void setSubtract(Double subtract) {
		this.subtract = subtract;
	}

	/**
	 * Get the 需要减去的已发放金额.
	 * 
	 * @return 需要减去的已发放金额
	 */
	public Double getSubtract() {
		return this.subtract;
	}

	/**
	 * Set the 打码比率.
	 * 
	 * @param ratio
	 *            打码比率
	 */
	public void setRatio(Double ratio) {
		this.ratio = ratio;
	}

	/**
	 * Get the 打码比率.
	 * 
	 * @return 打码比率
	 */
	public Double getRatio() {
		return this.ratio;
	}

	/**
	 * Set the 打码开始日期.
	 * 
	 * @param starttime
	 *            打码开始日期
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * Get the 打码开始日期.
	 * 
	 * @return 打码开始日期
	 */
	public Date getStarttime() {
		return this.starttime;
	}

	/**
	 * Set the 打码结束日期.
	 * 
	 * @param endtime
	 *            打码结束日期
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * Get the 打码结束日期.
	 * 
	 * @return 打码结束日期
	 */
	public Date getEndtime() {
		return this.endtime;
	}

	/**
	 * Set the 报表日期.
	 * 
	 * @param reporttime
	 *            报表日期
	 */
	public void setReporttime(Date reporttime) {
		this.reporttime = reporttime;
	}

	/**
	 * Get the 报表日期.
	 * 
	 * @return 报表日期
	 */
	public Date getReporttime() {
		return this.reporttime;
	}

	/**
	 * Set the 游戏类型.
	 * 
	 * @param gametype
	 *            游戏类型
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏类型.
	 * 
	 * @return 游戏类型
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 打码发放状态 1未发放 2已发放.
	 * 
	 * @param status
	 *            打码发放状态 1未发放 2已发放
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the 打码发放状态 1未发放 2已发放.
	 * 
	 * @return 打码发放状态 1未发放 2已发放
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportcode == null) ? 0 : reportcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReportWeeklyAgent other = (ReportWeeklyAgent) obj;
		if (reportcode == null) {
			if (other.reportcode != null) {
				return false;
			}
		} else if (!reportcode.equals(other.reportcode)) {
			return false;
		}
		return true;
	}

	public String getGameplatform() {
		return gameplatform;
	}

	public void setGameplatform(String gameplatform) {
		this.gameplatform = gameplatform;
	}

	public String getPaytype() {
		return paytype;
	}

	public void setPaytype(String paytype) {
		this.paytype = paytype;
	}

	public String getPatchno() {
		return patchno;
	}

	public void setPatchno(String patchno) {
		this.patchno = patchno;
	}

	public Double getActual() {
		return actual;
	}

	public void setActual(Double actual) {
		this.actual = actual;
	}
	public String getPayno() {
		return payno;
	}

	public void setPayno(String payno) {
		this.payno = payno;
	}
}
