package com.maven.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


/**
 * Model class of report_daily_agent.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportDailyAgent implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	private Integer reportcode;

	/** 企业编码. */
	private String enterprisecode;

	/** 品牌编码. */
	private String brandcode;

	/** 员工编码. */
	private String employeecode;

	/**  上级员工编码. */
	private String parentemployeecode;

	/** 用户账户. */
	private String loginaccount;

	/** 投注量. */
	private BigDecimal bet;

	/** 打码金额. */
	private BigDecimal amount;

	/** 打码比率. */
	private BigDecimal ratio;

	/** 打码日期. */
	private Date time;

	/** 报表日期. */
	private Date reporttime;

	/** 游戏平台. */
	private String gameplatform;
	
	/** 游戏类型. */
	private String gametype;

	/** 打码发放状态. */
	private String status;
	
	/** 支付单号，可用于回滚事务. */
	private String payno;
	
	
	/** 是否已代理周结 */
	private Boolean isWeeklyAgent;
	public enum Enum_isWeeklyAgent{
		未周结(false,"未周结"),
		已周结(true,"已周结");
		public Boolean value;
		public String desc;
		
		private Enum_isWeeklyAgent(Boolean value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}
	
	public enum Enum_status{
		未发放("1","未发放"),
		已发放("2","已发放"),
		周结汇总("3","周结汇总");
		public String value;
		public String desc;
        private Enum_status(String value,String desc) {
            this.value = value;
            this.desc = desc;
        }
        public static Enum_status getStatus(String status){
        	for (Enum_status e : Enum_status.values()) {
				if(e.value.endsWith("1")) return e;
			}
        	return null;
        }
	}
	
	
	/**
	 * Constructor.
	 */
	public ReportDailyAgent() {
	}
	
	/**
	 * Constructor.
	 */
	public ReportDailyAgent(String enterprisecode, String brandcode, String employeecode,
			String parentemployeecode, String loginaccount, BigDecimal bet, BigDecimal amount, BigDecimal ratio, Date time,
			Date reporttime, String gameplatform, String gametype, String status) {
		super();
		this.enterprisecode = enterprisecode;
		this.brandcode = brandcode;
		this.employeecode = employeecode;
		this.parentemployeecode = parentemployeecode;
		this.loginaccount = loginaccount;
		this.bet = bet;
		this.amount = amount;
		this.ratio = ratio;
		this.time = time;
		this.reporttime = reporttime;
		this.gameplatform = gameplatform;
		this.gametype = gametype;
		this.status = status;
	}

	/**
	 * Set the 主键.
	 * 
	 * @param reportcode
	 *            主键
	 */
	public void setReportcode(Integer reportcode) {
		this.reportcode = reportcode;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public Integer getReportcode() {
		return this.reportcode;
	}

	/**
	 * Set the 企业编码.
	 * 
	 * @param enterprisecode
	 *            企业编码
	 */
	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	/**
	 * Get the 企业编码.
	 * 
	 * @return 企业编码
	 */
	public String getEnterprisecode() {
		return this.enterprisecode;
	}

	/**
	 * Set the 品牌编码.
	 * 
	 * @param brandcode
	 *            品牌编码
	 */
	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	/**
	 * Get the 品牌编码.
	 * 
	 * @return 品牌编码
	 */
	public String getBrandcode() {
		return this.brandcode;
	}

	/**
	 * Set the 员工编码.
	 * 
	 * @param employeecode
	 *            员工编码
	 */
	public void setEmployeecode(String employeecode) {
		this.employeecode = employeecode;
	}

	/**
	 * Get the 员工编码.
	 * 
	 * @return 员工编码
	 */
	public String getEmployeecode() {
		return this.employeecode;
	}

	/**
	 * Set the  上级员工编码.
	 * 
	 * @param parentemployeecode
	 *             上级员工编码
	 */
	public void setParentemployeecode(String parentemployeecode) {
		this.parentemployeecode = parentemployeecode;
	}

	/**
	 * Get the  上级员工编码.
	 * 
	 * @return  上级员工编码
	 */
	public String getParentemployeecode() {
		return this.parentemployeecode;
	}

	/**
	 * Set the 用户账户.
	 * 
	 * @param loginaccount
	 *            用户账户
	 */
	public void setLoginaccount(String loginaccount) {
		this.loginaccount = loginaccount;
	}

	/**
	 * Get the 用户账户.
	 * 
	 * @return 用户账户
	 */
	public String getLoginaccount() {
		return this.loginaccount;
	}

	/**
	 * Set the 投注量.
	 * 
	 * @param bet
	 *            投注量
	 */
	public void setBet(BigDecimal bet) {
		this.bet = bet;
	}

	/**
	 * Get the 投注量.
	 * 
	 * @return 投注量
	 */
	public BigDecimal getBet() {
		return this.bet;
	}

	/**
	 * Set the 打码金额.
	 * 
	 * @param amount
	 *            打码金额
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * Get the 打码金额.
	 * 
	 * @return 打码金额
	 */
	public BigDecimal getAmount() {
		return this.amount;
	}

	/**
	 * Set the 打码比率.
	 * 
	 * @param ratio
	 *            打码比率
	 */
	public void setRatio(BigDecimal ratio) {
		this.ratio = ratio;
	}

	/**
	 * Get the 打码比率.
	 * 
	 * @return 打码比率
	 */
	public BigDecimal getRatio() {
		return this.ratio;
	}

	/**
	 * Set the 打码日期.
	 * 
	 * @param time
	 *            打码日期
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * Get the 打码日期.
	 * 
	 * @return 打码日期
	 */
	public Date getTime() {
		return this.time;
	}

	/**
	 * Set the 报表日期.
	 * 
	 * @param reporttime
	 *            报表日期
	 */
	public void setReporttime(Date reporttime) {
		this.reporttime = reporttime;
	}

	/**
	 * Get the 报表日期.
	 * 
	 * @return 报表日期
	 */
	public Date getReporttime() {
		return this.reporttime;
	}

	/**
	 * Set the 游戏平台.
	 * 
	 * @param gametype
	 *            游戏平台
	 */
	public void setGameplatform(String gameplatform) {
		this.gameplatform = gameplatform;
	}
	
	/**
	 * Get the 游戏平台.
	 * 
	 * @return 游戏平台
	 */
	public String getGameplatform() {
		return this.gameplatform;
	}
	
	/**
	 * Set the 游戏类型.
	 * 
	 * @param gametype
	 *            游戏类型
	 */
	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	/**
	 * Get the 游戏类型.
	 * 
	 * @return 游戏类型
	 */
	public String getGametype() {
		return this.gametype;
	}

	/**
	 * Set the 打码发放状态.
	 * 
	 * @param status
	 *            打码发放状态
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the 打码发放状态.
	 * 
	 * @return 打码发放状态
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportcode == null) ? 0 : reportcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReportDailyAgent other = (ReportDailyAgent) obj;
		if (reportcode == null) {
			if (other.reportcode != null) {
				return false;
			}
		} else if (!reportcode.equals(other.reportcode)) {
			return false;
		}
		return true;
	}

	public Boolean getIsWeeklyAgent() {
		return isWeeklyAgent;
	}

	public void setIsWeeklyAgent(Boolean isWeeklyAgent) {
		this.isWeeklyAgent = isWeeklyAgent;
	}
	public String getPayno() {
		return payno;
	}

	public void setPayno(String payno) {
		this.payno = payno;
	}
}
