package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of thirdparty_payment_type.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ThirdpartyPaymentType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 第三方支付类型编码. */
	private String thirdpartypaymenttypecode;

	/** 第三方支付类型名称. */
	private String thirdpartypaymenttypename;

	/** 状态. */
	private String status;

	/** 数据状态. */
	private String datastatus;
	
	
	public enum Enum_ThirdpartyPaymentType{
		通汇支付("P001","通汇支付"),
		易宝支付("P002","易宝支付"),
		通汇_微信("P003","通汇_微信"),
		乐盈支付("P004","乐盈支付"),
		优付支付("P005","优付支付"),
		JPAY支付("P006","JPAY支付"),
		通汇_支付宝("P007","通汇_支付宝"),
		银宝支付("P008","银宝支付"),
		乐付支付("P009","乐付支付"),
		
		新贝网关("P010","新贝网关"),
		新贝微信("P011","新贝微信"),
		新贝支付宝("P012","新贝支付宝"),
		
		国盛通("P013","国盛通"),
		捷付通("P014","捷付通"),
		
		
		SD银联("P016","SD银联"),
		SD微信("P017","SD微信"),
		SD支付宝("P018","SD支付宝"),
		SD付款("P019","SD付款"),
		SD网银P2P("P020","SD网银P2P"),
		
		牛付网关("P021","牛付网关"),
		牛付微信支付宝("P022","牛付微信支付宝"),
		
        华仁网银("P023", "华仁网银"), 
        华仁微信支付宝("P024", "华仁微信支付宝"),
        华仁代付("P025", "华仁代付"),

		极付网银("P027","极付网银"),//含网银支付，快捷支付，微信扫码支付，支付宝扫码支付 和付款接口，同一商户
		极付快捷支付("P028","极付快捷支付"),//含网银支付，快捷支付，微信扫码支付，支付宝扫码支付 和付款接口，同一商户
		极付微信支付宝("P029","极付微信支付宝"),//含网银支付，快捷支付，微信扫码支付，支付宝扫码支付 和付款接口，同一商户
		极付出款("P030","极付出款"),
		
		摩宝支付("P031","摩宝支付"),
		
		乐付微信("P032","乐付微信"),
		云盛支付("P033","云盛支付"),//支持=1网银,2支付，3微信，4 QQ钱包
		乐付出款("P034","乐付出款"),
		汇潮支付("P035","汇潮支付"),
		
		智付网银("P015","智付网银"),
		智付微信支付宝("P036","智付微信支付宝"),
		
		秒付网银("P037", "秒付支付"),
		秒付微信("P038", "秒付微信"),
		秒付支付宝("P039", "秒付支付宝"),
		
		乐信付PC收银台("P040", "乐信PC收银台"),
		乐信付H5收银台("P043", "乐信H5收银台"),
		
		如意网关支付("P041", "如意网关支付"),
		如意微信支付宝("P042", "如意微信支付宝"),
		如意京东钱包("P093", "如意京东钱包"),
		如意代付("P044", "如意代付"),
		
		乐付支付宝("P045", "乐付支付宝"),
		乐付QQ钱包("P046", "乐付QQ钱包"),
		
		锐付网银("P047", "锐付网银"),
		锐付微信支付宝("P048", "锐付微信支付宝"),
		锐付出款("P074", "锐付出款"),
		
		宝立付网银("P049", "宝立付网银"),
		宝立付微信支付宝("P050", "宝立付微信支付宝"),
		
		可可网银("P051", "可可网银支付"),
		可可微信支付宝("P052", "可可微信支付宝支付"),
		
		喜发网银("P053", "喜发网银支付"),
		喜发微信支付宝("P054", "喜发微信支付宝支付"),
		喜发代付("P055", "喜发代付接口"),
		
		众宝支付("P056", "众宝支付"),
		众宝微信支付宝("P057", "众宝微信支付宝支付"),
		众宝支付H5("P073", "众宝微信支付宝H5版"),
		
		旺付通网银("P058", "旺付通网银"),
		旺付通微信支付宝("P059", "旺付通微信支付宝"),
		旺付通银联扫码("P083", "旺付通银联扫码"),
		旺付通京东钱包("P084", "旺付通京东钱包"),
		旺付通代付("P082", "旺付通代付接口"),
		
		亿卡云网银("P060", "亿卡云网银支付"),
		亿卡云微信支付宝("P061", "亿卡云微信支付宝"),
		
		聚合支付("P062", "聚合支付"),
		
		点点支付("P063", "点点支付"),
		点点代付("P064", "点点代付"),
		
		Astropay支付("P065", "Astropay支付"),
		Astropay出款("P066", "Astropay出款"),
		
		聚合快捷支付("P067", "聚合快捷支付"),
		聚合出款("P068", "聚合出款"),
		
		付呗支付("P069", "付呗支付"),
		
		支付通网银("P070", "支付通网银"),
		支付通微信支付宝("P071", "支付通微信支付宝"),
		支付通代付("P072", "支付通代付"),
		
		银盛支付宝H5("P075", "银盛支付宝H5"),
		银盛代付("P076", "银盛代付"),
		
		聚合收银台("P077", "聚合收银台"),
		
		星付网银("P078", "星付网银接口"),
		星付扫码("P079", "星付扫码接口"),
		星付银联扫码("P085", "星付银联扫码"),
		星付H5("P080", "星付H5支付接口"),
		星付代付("P081", "星付代付接口"),
		
		亿联支付("P086", "亿联支付"),
		亿联扫码("P087", "亿联扫码"),
		亿联代付("P088", "亿联代付"),
		
		多多网银("P089", "多多网银接口"),
		多多扫码("P090", "多多扫码接口"),
		多多WAP("P091", "多多wap接口"),
		多多代付("P092", "多多代付"),
		多多京东("P094", "多多京东钱包"),
		
		信付通网银("P095", "信付通网银"),
		信付通扫码("P096", "信付通扫码"),
		信付通京东("P097", "信付通京东"),
		信付通代付("P098", "信付通代付"),
		
		畅汇网银("P099","畅汇网银"),
		畅汇微信支付宝("P100","畅汇微信支付宝"),
		畅汇快捷支付("P101","畅汇快捷支付"),
		畅汇QQ钱包("P102","畅汇QQ钱包"),
		畅汇畅码支付("P103","畅汇畅码支付"),
		
		神奇支付("P104", "聚合支付-金塔"),
		神奇扫码("P105", "聚合支付-金塔"),
		神奇京东("P106", "聚合支付-金塔"),
		神奇银联("P107", "聚合支付-金塔"),
		神奇代付("P108", "聚合代付-金塔"),
		
		;
		public String value;
		public String desc;
		
		private Enum_ThirdpartyPaymentType(String value,String desc){
			this.value=value;
			this.desc=desc;
		}
	}

	/**
	 * Constructor.
	 */
	public ThirdpartyPaymentType() {
	}

	/**
	 * Set the 第三方支付类型编码.
	 * 
	 * @param thirdpartypaymenttypecode
	 *            第三方支付类型编码
	 */
	public void setThirdpartypaymenttypecode(String thirdpartypaymenttypecode) {
		this.thirdpartypaymenttypecode = thirdpartypaymenttypecode;
	}

	/**
	 * Get the 第三方支付类型编码.
	 * 
	 * @return 第三方支付类型编码
	 */
	public String getThirdpartypaymenttypecode() {
		return this.thirdpartypaymenttypecode;
	}

	/**
	 * Set the 第三方支付类型名称.
	 * 
	 * @param thirdpartypaymenttypename
	 *            第三方支付类型名称
	 */
	public void setThirdpartypaymenttypename(String thirdpartypaymenttypename) {
		this.thirdpartypaymenttypename = thirdpartypaymenttypename;
	}

	/**
	 * Get the 第三方支付类型名称.
	 * 
	 * @return 第三方支付类型名称
	 */
	public String getThirdpartypaymenttypename() {
		return this.thirdpartypaymenttypename;
	}

	/**
	 * Set the 状态.
	 * 
	 * @param status
	 *            状态
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the 状态.
	 * 
	 * @return 状态
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * Set the 数据状态.
	 * 
	 * @param datastatus
	 *            数据状态
	 */
	public void setDatastatus(String datastatus) {
		this.datastatus = datastatus;
	}

	/**
	 * Get the 数据状态.
	 * 
	 * @return 数据状态
	 */
	public String getDatastatus() {
		return this.datastatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((thirdpartypaymenttypecode == null) ? 0 : thirdpartypaymenttypecode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ThirdpartyPaymentType other = (ThirdpartyPaymentType) obj;
		if (thirdpartypaymenttypecode == null) {
			if (other.thirdpartypaymenttypecode != null) {
				return false;
			}
		} else if (!thirdpartypaymenttypecode.equals(other.thirdpartypaymenttypecode)) {
			return false;
		}
		return true;
	}

}

