package com.maven.entity;

import java.io.Serializable;

/**
 * Model class of thirdparty_payment_type_setting.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ThirdpartyPaymentTypeSetting implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 第三方支付参数编码. */
	private String paymentsettingcode;

	/** 第三方支付编码. */
	private String thirdpartypaymenttypecode;

	/** 参数字段. */
	private String argumentfiled;

	/** 参数描述. */
	private String argumentdesc;

	/** 数据状态. */
	private String datastatus;

	/**
	 * Constructor.
	 */
	public ThirdpartyPaymentTypeSetting() {
	}

	/**
	 * Set the 第三方支付参数编码.
	 * 
	 * @param paymentsettingcode
	 *            第三方支付参数编码
	 */
	public void setPaymentsettingcode(String paymentsettingcode) {
		this.paymentsettingcode = paymentsettingcode;
	}

	/**
	 * Get the 第三方支付参数编码.
	 * 
	 * @return 第三方支付参数编码
	 */
	public String getPaymentsettingcode() {
		return this.paymentsettingcode;
	}

	/**
	 * Set the 第三方支付编码.
	 * 
	 * @param thirdpartypaymentcode
	 *            第三方支付编码
	 */
	public void setThirdpartypaymenttypecode(String thirdpartypaymenttypecode) {
		this.thirdpartypaymenttypecode = thirdpartypaymenttypecode;
	}

	/**
	 * Get the 第三方支付编码.
	 * 
	 * @return 第三方支付编码
	 */
	public String getThirdpartypaymenttypecode() {
		return this.thirdpartypaymenttypecode;
	}

	/**
	 * Set the 参数字段.
	 * 
	 * @param argumentfiled
	 *            参数字段
	 */
	public void setArgumentfiled(String argumentfiled) {
		this.argumentfiled = argumentfiled;
	}

	/**
	 * Get the 参数字段.
	 * 
	 * @return 参数字段
	 */
	public String getArgumentfiled() {
		return this.argumentfiled;
	}

	/**
	 * Set the 参数描述.
	 * 
	 * @param argumentdesc
	 *            参数描述
	 */
	public void setArgumentdesc(String argumentdesc) {
		this.argumentdesc = argumentdesc;
	}

	/**
	 * Get the 参数描述.
	 * 
	 * @return 参数描述
	 */
	public String getArgumentdesc() {
		return this.argumentdesc;
	}

	/**
	 * Set the 数据状态.
	 * 
	 * @param datastatus
	 *            数据状态
	 */
	public void setDatastatus(String datastatus) {
		this.datastatus = datastatus;
	}

	/**
	 * Get the 数据状态.
	 * 
	 * @return 数据状态
	 */
	public String getDatastatus() {
		return this.datastatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((paymentsettingcode == null) ? 0 : paymentsettingcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ThirdpartyPaymentTypeSetting other = (ThirdpartyPaymentTypeSetting) obj;
		if (paymentsettingcode == null) {
			if (other.paymentsettingcode != null) {
				return false;
			}
		} else if (!paymentsettingcode.equals(other.paymentsettingcode)) {
			return false;
		}
		return true;
	}

}
