package com.maven.entity;

import java.io.Serializable;
import java.util.Date;

import com.maven.entity.TakeDepositRecord.Enum_ordertype;

/**
 * Model class of 工作流程配置表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class WorkingFlowConfiguration implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 流程编号. */
	private String flowcode;
	
	/** 流程名称. */
	private String flowname;
	
	/** 企业编号 */
	private String enterprisecode;
	
	/** 工作流创建品牌 */
	private String brandcode;

	/** 流程标志. */
	private Short flowtype;

	/** 是否启用. */
	private Short enable;

	/** 流程顺序. */
	private Short flowsort;

	/** 流程启动条件. */
	private Integer flowthreshold;
	
	/** 处理时长 */
	private Integer handletime;

	/** 创建时间. */
	private Date createtime;

	/** 状态. */
	private Short datastatus;
	
	/** 品牌名称. */
	private String brandname;
	
	/* 加密唯一标识列 */
	private String sign;
	
	public enum Enum_flowtype{
		取款工作流(1,"取款工作流"),
		存款工作流(2,"存款工作流");
		public int value;
        public String desc;
        private Enum_flowtype(int _value, String _desc) {
            this.value = _value;
            this.desc = _desc;
        }
        public String getDesc() {  
            return desc;  
        } 
        public int getValue() {  
            return value;  
        }  
        
        public static Enum_flowtype getFlowType(Object object){
        	if(object instanceof Enum_ordertype){
        		Enum_ordertype e = (Enum_ordertype)object;
        		if(e.value==Enum_ordertype.取款.value) return Enum_flowtype.取款工作流;
        		if(e.value==Enum_ordertype.存款.value) return Enum_flowtype.存款工作流;
        	}
        	return null;
        }
        
	}

	    
	/**
	 * Set the 流程编号.
	 * 
	 * @param flowcode
	 *            流程编号
	 */
	public void setFlowcode(String flowcode) {
		this.flowcode = flowcode;
	}
	
	/**
	 * Get the 流程编号.
	 * 
	 * @return 流程编号
	 */
	public String getFlowcode() {
		return this.flowcode;
	}

	public String getFlowname() {
		return flowname;
	}

	public void setFlowname(String flowname) {
		this.flowname = flowname;
	}
	
	
	
	/**
	 * Set the 流程标志.
	 * 
	 * @param flowtype
	 *            流程标志
	 */
	public void setFlowtype(Short flowtype) {
		this.flowtype = flowtype;
	}

	/**
	 * Get the 流程标志.
	 * 
	 * @return 流程标志
	 */
	public Short getFlowtype() {
		return this.flowtype;
	}


	/**
	 * Set the 是否启用.
	 * 
	 * @param enable
	 *            是否启用
	 */
	public void setEnable(Short enable) {
		this.enable = enable;
	}

	/**
	 * Get the 是否启用.
	 * 
	 * @return 是否启用
	 */
	public Short getEnable() {
		return this.enable;
	}

	/**
	 * Set the 流程顺序.
	 * 
	 * @param flowsort
	 *            流程顺序
	 */
	public void setFlowsort(Short flowsort) {
		this.flowsort = flowsort;
	}

	/**
	 * Get the 流程顺序.
	 * 
	 * @return 流程顺序
	 */
	public Short getFlowsort() {
		return this.flowsort;
	}

	/**
	 * Set the 流程启动条件.
	 * 
	 * @param flowthreshold
	 *            流程启动条件
	 */
	public void setFlowthreshold(Integer flowthreshold) {
		this.flowthreshold = flowthreshold;
	}

	/**
	 * Get the 流程启动条件.
	 * 
	 * @return 流程启动条件
	 */
	public Integer getFlowthreshold() {
		return this.flowthreshold;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((flowcode == null) ? 0 : flowcode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		WorkingFlowConfiguration other = (WorkingFlowConfiguration) obj;
		if (flowcode == null) {
			if (other.flowcode != null) {
				return false;
			}
		} else if (!flowcode.equals(other.flowcode)) {
			return false;
		}
		return true;
	}
	public Integer getHandletime() {
		return handletime;
	}
	public void setHandletime(Integer handletime) {
		this.handletime = handletime;
	}

	public String getBrandcode() {
		return brandcode;
	}

	public void setBrandcode(String brandcode) {
		this.brandcode = brandcode;
	}

	public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public String getEnterprisecode() {
		return enterprisecode;
	}

	public void setEnterprisecode(String enterprisecode) {
		this.enterprisecode = enterprisecode;
	}

	public Short getDatastatus() {
		return datastatus;
	}

	public void setDatastatus(Short datastatus) {
		this.datastatus = datastatus;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

}
